Repository kubernetes-sigs/image-builder, pull requests merged in 2019-10, with the labels that each got.

#61 OVA: parameterize network name
  images/capi/packer/ova/esx.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#65 enable building CAPI packer images using AWS_PROFILE env variable
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#63 Add OWNERS file to images/capi
  OWNERS_ALIASES
  images/capi/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#67 OVA: unify definition of output directory
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 fix AMI names for CAPI AMI image build
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#49 Azure support
  images/capi/Makefile
  images/capi/packer/azure/azure-config.json
  images/capi/packer/azure/azure-sig-ubuntu-1804.json
  images/capi/packer/azure/azure-vhd-ubuntu-1804.json
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 [capi] Azure: add docs and fix image version
  images/capi/packer/azure/README.md
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#77 Bump Containerd version to 1.3.0
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Add Goals & Roadmap to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#80 Add gsutil to GCE based images
  images/capi/ansible/roles/providers/tasks/googlecompute.yml
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#72 [imagebuilder] update AWS base images
  images/kube-deploy/imagebuilder/pkg/imagebuilder/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#82 fix typos and meeting notes link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#84 Lock default user before shutdown OVA VM
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#87 🏃Bump Kubernetes version to 16.2 in packer config
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 Update CentOS ISO from 7.6 to 7.7.
  images/capi/packer/ova/ova-centos-7.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Fix CentOS ISO download link
  images/capi/packer/ova/ova-centos-7.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#45 OVA: Make CentOS kickstart not rely on internet
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
Labels: approved, cncf-cla: yes, lgtm, size/M
