Repository kubernetes-sigs/image-builder, pull requests merged in 2019-08, with the labels that each got.

#14 update the ubuntu iso url
  images/capi/config/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#15 Add @figo to @codenrhoden OWNER file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#16 Allow customize kubernetes, cni source
  images/capi/Makefile
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/url.yml
  images/capi/config/cni.json
  images/capi/config/kubernetes.json
  images/capi/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#19 pass kubernetes_deb_repo var to ansible
  images/capi/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#23 import ami builder from CAPA repo
  images/capi/.gitignore
  images/capi/Makefile
  images/capi/README.md
  images/capi/packer/ami/Makefile
  images/capi/packer/ami/README.md
  images/capi/packer/ami/ami-base-images-us-east-1.json
  images/capi/packer/ami/packer.json
  images/capi/packer/config/cni.json
  images/capi/packer/config/kubernetes.json
  images/capi/packer/ova/README.md
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
  images/capi/packer/ova/linux/ubuntu/http/18.04/preseed.cfg
  images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg
  images/capi/packer/ova/ova-centos-7.json
  images/capi/packer/ova/ova-ubuntu-1804.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#24 fix makefile
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#25 [capi images] Expose containerd version variables through packer
  images/capi/Makefile
  images/capi/README.md
  images/capi/ansible/roles/containerd/defaults/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/config/containerd.json
  images/capi/packer/ova/README.md
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M
