Repository kubernetes-sigs/image-builder, pull requests merged in 2019-09, with the labels that each got.

#28 Fix for AMI build to detect Amazon Linux
  images/capi/ansible/roles/common/tasks/redhat.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#29 Build CAPI Ubuntu image for GCE
  images/capi/Makefile
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/packer/config/kubernetes.json
  images/capi/packer/gce/Makefile
  images/capi/packer/gce/gce-default.json
  images/capi/packer/gce/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#33 remove centos default root password access
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
Labels: approved, cncf-cla: yes, lgtm, size/XS

#34 kube-deploy: Update paths so that builds correctly in new location
  images/kube-deploy/imagebuilder/Dockerfile
  images/kube-deploy/imagebuilder/Makefile
  images/kube-deploy/imagebuilder/README.md
  images/kube-deploy/imagebuilder/glide.yaml
  images/kube-deploy/imagebuilder/go.mod
  images/kube-deploy/imagebuilder/go.sum
  images/kube-deploy/imagebuilder/main.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/aws.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/builder.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/cloud.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/gce.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#35 Don't .gitignore pkg/imagebuilder
  .gitignore
  images/kube-deploy/imagebuilder/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#36 Better log messages
  images/kube-deploy/imagebuilder/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#37 kube-deploy: Add k8s 1.13 and 1.14 images
  images/kube-deploy/imagebuilder/aws-1.13-stretch.yaml
  images/kube-deploy/imagebuilder/aws-1.14-stretch.yaml
  images/kube-deploy/imagebuilder/templates/1.13-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.14-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#38 kube-deploy: Add 1.15 images
  images/kube-deploy/imagebuilder/aws-1.15-stretch.yaml
  images/kube-deploy/imagebuilder/templates/1.15-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#42 Support for configuration of non-default VPC and Subnet
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#46 Support for non-default containerd download URL
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#44 Add ability to inject/remove extra repos
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/debian.yml
  images/capi/ansible/roles/common/tasks/redhat.yml
  images/capi/ansible/roles/sysprep/defaults/main.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Add ability to disable existing repos
  images/capi/ansible/playbook.yml
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/debian.yml
  images/capi/ansible/roles/common/tasks/redhat.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 Add targets to build images on remote ESX host
  images/capi/Makefile
  images/capi/packer/ova/esx.json
  images/capi/packer/ova/ova-ubuntu-1804.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 [images/capi] Remove forked version of cloud-init
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/files/cloud.cfg
  images/capi/ansible/roles/common/tasks/debian.yml
  images/capi/ansible/roles/common/tasks/redhat.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/goss/goss.yaml
  images/capi/packer/goss/redhat-vars.yaml
  images/capi/packer/goss/ubuntu-vars.yaml
  images/capi/packer/ova/ova-centos-7.json
  images/capi/packer/ova/ova-ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 kube-deploy: remove (unused) glide.lock and glide.yaml
  images/kube-deploy/imagebuilder/glide.lock
  images/kube-deploy/imagebuilder/glide.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 kube-deploy: Move from glog to klog
  images/kube-deploy/imagebuilder/go.mod
  images/kube-deploy/imagebuilder/go.sum
  images/kube-deploy/imagebuilder/main.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/aws.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/config.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/executor/interface.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/executor/local.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/executor/ssh.go
  images/kube-deploy/imagebuilder/pkg/imagebuilder/gce.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#51 Revert #29 on packer_builder_type
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#55 kube-deploy: alias imports for goimports
  images/kube-deploy/imagebuilder/pkg/imagebuilder/gce.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#56 kube-deploy: no need to hack alsologtostderr=true flag
  images/kube-deploy/imagebuilder/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#52 [capi] Rev versions
  images/capi/packer/ami/packer.json
  images/capi/packer/config/containerd.json
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#57 Only download k8s images from http when user want
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/ansible/roles/kubernetes/tasks/kubeadmpull.yml
  images/capi/ansible/roles/kubernetes/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#58 Fix 'make clean' failure in Makefile
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#60 OVA: set VMX version to 13
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M
