Repository kubernetes-sigs/image-builder, pull requests merged in 2020-08, with the labels that each got.

#317 Specify AMI root volume device name for all distributions
  images/capi/packer/ami/amazon-2.json
  images/capi/packer/ami/centos-7.json
  images/capi/packer/ami/packer.json
  images/capi/packer/ami/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#318 Add make-deps as dependency to image building targets
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#316 Disable Hyper-V KVP daemon for Ubuntu AMI
  images/capi/ansible/roles/providers/tasks/aws.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#319 Increase Bandwidth for TCP to 1MB on Photon OS
  images/capi/ansible/roles/node/tasks/photon.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#321 Update GOSS Provisioner version
  images/capi/hack/ensure-goss.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#322 Add GOSS docs
  docs/book/src/SUMMARY.md
  docs/book/src/capi/goss/goss.md
  docs/book/src/glossary.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#312 Remove potential python2 fallbacks
  images/capi/hack/ensure-ansible.sh
  images/capi/hack/ensure-azure-cli.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#323 Add notify type to containerd systemd unit file
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/boot-order.conf
  images/capi/ansible/roles/providers/files/etc/systemd/system/cloud-config.service.d/boot-order.conf
  images/capi/ansible/roles/providers/files/etc/systemd/system/cloud-final.service.d/boot-order.conf
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#324 Enable all cloud-init services on boot (all OS)
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#330 Fix ensure Py3, Pip3, and azure-cli
  images/capi/hack/ensure-ansible.sh
  images/capi/hack/ensure-azure-cli.sh
  images/capi/hack/utils.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#329 Add Packer build color option
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#325 Refactor Azure packer builder
  images/capi/Makefile
  images/capi/packer/azure/centos-7.json
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#328 Allow multiple custom roles
  docs/book/src/capi/capi.md
  images/capi/ansible/haproxy.yml
  images/capi/ansible/node.yml
  images/capi/packer/config/ansible-args.json
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#294 Added cfg file for cloud-init to improve usability
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/05_logging.cfg
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#307 Add OS & provider specific GOSS validations
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-kernel-params.yaml
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#334 bump default K8s to 1.16.14
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 Add extra_rpms back for Azure
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 Change default ova vmx_version from 13 to 15
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/packer-common.json
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#338 Update Photon ISO to Rev 2 Update 3
  images/capi/packer/ova/photon-3.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 Common packer vars and var validation
  images/capi/Makefile
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/common.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer-common.json
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#343 Fix call to sha256sum on Linux
  images/capi/hack/utils.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Add RHEL 7 support
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/ansible/roles/setup/tasks/redhat.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/hack/image-build-ova.py
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
  images/capi/packer/ova/linux/rhel
  images/capi/packer/ova/rhel-7.json
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, size/M

#345 Fix Azure CentOS build
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/scripts/ci-azure-e2e.sh
  images/capi/packer/config/common.json
  images/capi/packer/ova/centos-7.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#346 Set sysctl params in a loop
  images/capi/ansible/roles/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#339 capi: suppress warnings on creating files without mode
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/debian.yml
  images/capi/ansible/roles/kubernetes/tasks/ecrpull.yml
  images/capi/ansible/roles/kubernetes/tasks/kubeadmpull.yml
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/photon.yml
  images/capi/ansible/roles/kubernetes/tasks/url.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/googlecompute.yml
  images/capi/ansible/roles/providers/tasks/qemu.yml
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/ansible/roles/setup/tasks/debian.yml
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/ansible/roles/setup/tasks/rpm_repos.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#344 Disable conntrackd service to reduce CPU utilization
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
