Repository kubernetes-sigs/image-builder, pull requests merged in 2020-09, with the labels that each got.

#351 Fix Azure build VHD pipeline to use manifest output
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#347 Add support to build Ubuntu 20.04 on AWS, Azure & Qemu
  images/capi/Makefile
  images/capi/ansible/roles/setup/tasks/debian.yml
  images/capi/packer/ami/ubuntu-2004.json
  images/capi/packer/azure/azure-sig.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/ubuntu-2004.json
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/qemu/qemu-ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#356 Azure pipelines: create multi stage pipeline
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/.pipelines/delete-storage-account.yaml
  images/capi/packer/azure/.pipelines/generate-sas.yaml
  images/capi/packer/azure/.pipelines/k8s-config.yaml
  images/capi/packer/azure/.pipelines/stages.yaml
  images/capi/packer/azure/.pipelines/vhd-publishing-info.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#358 Azure pipeline: rename K8S_VERSION var to KUBERNETES_VERSION
  images/capi/packer/azure/scripts/new-sku.sh
  images/capi/packer/azure/ubuntu-sku-template.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#359 Azure: update pub to v0.2.5
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#360 Azure: update pub to v0.2.6
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#361 :bug: Updates Ubuntu ISO to current 18.04 release (old one is gone)
  images/capi/packer/ova/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#362 CAPI: Bump kubernetes-cni version to v0.8.7
  images/capi/packer/config/cni.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#353 Update OVF spec for new hardware version
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#366 Update HAProxy OVF for new hardware version
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/L

#367 :bug: Forces python3 for ova script post processor
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 Update packer-prov-goss to version 2.0.0
  images/capi/hack/ensure-goss.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#364 Azure pipeline: only run SKU stage if VHD stage succeeds
  images/capi/packer/azure/.pipelines/stages.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 CAPI: Update default k8s version to 1.17.11
  docs/book/src/capi/capi.md
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#373 Add auditd for Ubuntu
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/amazonLinux2.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/node/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#376 Makefile: Introduce ON_ERROR_ASK for debugging
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#331 Truncate log files instead of deleting all dirs in /var/log
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#383 update containerd to 1.4.1
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/containerd.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#380 CAPI: Add more digitalocean images
  docs/book/src/capi/providers/digitalocean.md
  images/capi/Makefile
  images/capi/packer/digitalocean/centos-7.json
  images/capi/packer/digitalocean/do-default.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/digitalocean/ubuntu-1804.json
  images/capi/packer/digitalocean/ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#352 Support building base VMDKs and build OVFs from the base VMDKs
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/vmx.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#385 Disable H/W tx offload for ethernet devices on Photon
  images/capi/ansible/roles/node/files/etc/udev/rules.d/90-netif-disable-hw-offload.rules
  images/capi/ansible/roles/node/tasks/photon.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#392 Update to latest Kubernetes version and cloud-init guestinfo_datasource version
  images/capi/cloudinit/user-data
  images/capi/packer/ova/packer-common.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
