Repository kubernetes-sigs/image-builder, pull requests merged in 2020-07, with the labels that each got.

#266 Move AMI builds to exclusively use Make
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/hack/image-build-ova.py
  images/capi/packer/ami/amazon-2.json
  images/capi/packer/ami/ami-default.json
  images/capi/packer/ami/centos-7.json
  images/capi/packer/ami/packer.json
  images/capi/packer/ami/ubuntu-1804.json
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#269 Add 'exclude-nics' filter in vmtools configuration file in Ansible
  images/capi/ansible/roles/providers/files/etc/vmware-tools/tools.conf
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#265 Add VC Datacenter as input var to Packer
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/vsphere.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#272 Language: use "main partition" for the resized partition
  images/kube-deploy/imagebuilder/templates/1.10-jessie.yml
  images/kube-deploy/imagebuilder/templates/1.11-jessie.yml
  images/kube-deploy/imagebuilder/templates/1.2.yml
  images/kube-deploy/imagebuilder/templates/1.3.yml
  images/kube-deploy/imagebuilder/templates/1.4.yml
  images/kube-deploy/imagebuilder/templates/1.5.yml
  images/kube-deploy/imagebuilder/templates/1.6.yml
  images/kube-deploy/imagebuilder/templates/1.7.yml
  images/kube-deploy/imagebuilder/templates/1.8-jessie.yml
  images/kube-deploy/imagebuilder/templates/1.9-jessie.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#271 Add auditd to photon OS
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/files/photon-os/etc/audit/rules.d/containerd.rules
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/node/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#286 Add GOSS provisioner to node OVA builder
  images/capi/Makefile
  images/capi/packer/ami/packer.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#288 Add pretty print option to GOSS output
  images/capi/Makefile
  images/capi/hack/ensure-goss.sh
  images/capi/packer/ami/packer.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#290 Move rng-tools package to Ansible from photon kickstart
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/packer/ova/linux/photon/http/3/ks.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#289 capi: remove iso_checksum_type in qemu for packer 1.6
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 kubeadm template to allow overriding the location.
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/ansible/roles/kubernetes/tasks/kubeadmpull.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#293 Allow customizing volume_size for AWS
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#296 legacy kops images: Stop prebaking kubelets
  images/kube-deploy/imagebuilder/templates/1.17-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.18-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#301 Make ensure-goss replace old goss provisioner version
  images/capi/hack/ensure-goss.sh
  images/capi/hack/utils.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#304 Bump docs and scripts to Packer v1.6.0
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/digitalocean.md
  docs/book/src/capi/providers/openstack.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/hack/ensure-packer.sh
  v1/README.md
  v1/examples/packerAws.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#302 :bug: Required volume sizes since it's now in a required position.
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#305 Add versions to GOSS spec
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/hack/ensure-goss.sh
  images/capi/packer/ami/packer.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-kernel-params.yaml
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/goss/goss.yaml
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#291 Add goss spec for checking k8s package and k8s image presence
  images/capi/packer/ami/packer.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/goss/goss-common.yaml
  images/capi/packer/goss/goss.yaml
  images/capi/packer/ova/packer-node.json
Labels: cncf-cla: yes, lgtm, size/M

#306 explicitly pass user: builder so that ansible does not default to root
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#309 Fix build name for ubuntu AMI to match cluster-api-provider-aws convention
  images/capi/packer/ami/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#308 Fix building of ami and ova for centos
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#310 capi: recommend Goss provisioner v1.2.0
  docs/book/src/capi/capi.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#300 Enable goss for Azure
  images/capi/Makefile
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S
