Repository kubernetes-sigs/image-builder, pull requests merged in 2020-04, with the labels that each got.

#196 Explicit installation of the latest SSMAgent
  images/capi/ansible/roles/providers/tasks/aws.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#201 [capi/Azure] Use pip3 to install Azure CLI
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 [capi/Azure] Add pipefail option to Azure pipeline build VHD step
  images/capi/packer/azure/.pipelines/build-vhd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#204 Enable rng-tools as default entropy gather in Photon images
  images/capi/packer/ova/linux/photon/http/3/ks.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#207 Add a flag to conditionally load additional kubernetes images when source type != pkg
  .gitignore
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/kubernetes.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 Add vsphere builder
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
  images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg
  images/capi/packer/ova/ova-centos-7.json
  images/capi/packer/ova/ova-photon-3.json
  images/capi/packer/ova/ova-ubuntu-1804.json
  images/capi/packer/ova/ova-ubuntu-2004.json
  images/capi/packer/ova/packer.json
  images/capi/packer/ova/vsphere.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#203 Clarify what belongs to the K8s node images
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/ansible/node.yml
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/debian.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/node/tasks/photon.yml
  images/capi/ansible/roles/node/tasks/redhat.yml
  images/capi/ansible/roles/node/tasks/rpm_repos.yml
  images/capi/ansible/roles/node/templates/etc/apt/sources.list.j2
  images/capi/ansible/roles/node/templates/photon_bash_profile
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/centos-7.json
  images/capi/packer/ova/packer.json
  images/capi/packer/ova/photon-3.json
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/ova/ubuntu-2004.json
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#209 Fix vsphere build still having the old naming scheme
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 For vsphere-iso the minimum packer version is 1.5.2
  images/capi/hack/ensure-packer.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#208 Update version of containerd to latest v1.3.4
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#195 Allows adding entire containerd configuration blocks
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#86 fix golint error
  images/kube-deploy/imagebuilder/pkg/imagebuilder/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#131 Fix imagebuilder docker build failure
  images/kube-deploy/imagebuilder/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#213 Precreate `kube-apiserver` audit log
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#219 Add emacs temp files to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 Fix provider role not running on vsphere builds
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 master2
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#223 ova: no need to symlink cloud-init in CentOS
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 Create setup role for package installation
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/setup/defaults/main.yml
  images/capi/ansible/roles/setup/tasks/debian.yml
  images/capi/ansible/roles/setup/tasks/main.yml
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/ansible/roles/setup/tasks/redhat.yml
  images/capi/ansible/roles/setup/tasks/rpm_repos.yml
  images/capi/ansible/roles/setup/templates/etc/apt/sources.list.j2
  images/capi/ansible/roles/setup/templates/photon_bash_profile
Labels: approved, cncf-cla: yes, lgtm, size/M

#214 Take over building HAProxy OVA from CAPV
  images/capi/Makefile
  images/capi/ansible/haproxy.yml
  images/capi/ansible/roles/haproxy/defaults/main.yml
  images/capi/ansible/roles/haproxy/files/etc/haproxy/haproxy.cfg
  images/capi/ansible/roles/haproxy/files/etc/systemd/system/haproxy.service.d/cloud-init.conf
  images/capi/ansible/roles/haproxy/meta/main.yml
  images/capi/ansible/roles/haproxy/tasks/main.yml
  images/capi/ansible/roles/pki/files/usr/local/bin/new-ca.sh
  images/capi/ansible/roles/pki/files/usr/local/bin/new-cert.sh
  images/capi/ansible/roles/pki/tasks/main.yml
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/linux/photon/http/3/ks.json
  images/capi/packer/ova/packer-common.json
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL
