Repository kubernetes-sigs/image-builder, pull requests merged in 2020-10, with the labels that each got.

#394 Add vsphere-clone builder to decrease build time
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/vsphere.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 Default to BBR TCP congestion control algorithm
  images/capi/ansible/roles/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#357 capi: update ansible version to 2.10
  docs/book/src/capi/capi.md
  images/capi/hack/ensure-ansible.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#403 Update openstack.md for Ubuntu 20.04 LTS
  docs/book/src/capi/providers/openstack.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#406 Set feature flag for Cloud Init 23 for Ubuntu systems for compatibility with Cluster API Provider AWS
  images/capi/ansible/roles/node/files/usr/lib/python3/dist-packages/cloudinit/feature_overrides.py
  images/capi/ansible/roles/node/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#410 Move cloud-init feature flag setting to providers role
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/feature_overrides.py
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#405 Update README to change office hours to Thu 08:00 PT
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#411 Revert "Disable H/W tx offload for ethernet devices on Photon"
  images/capi/ansible/roles/node/files/etc/udev/rules.d/90-netif-disable-hw-offload.rules
  images/capi/ansible/roles/node/tasks/photon.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#371 capi: install crictl from upstream cri-tools repo
  images/capi/ansible/roles/kubernetes/tasks/crictl-url.yml
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/kubernetes.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#414 fix hardcoding of gallery name when creating image definition
  images/capi/packer/azure/scripts/init-sig.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#418 Make default Azure storage account name unique and check name before create
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#416 🌱 Update capi deps target
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#401 skip post-processors when building base vmx locally
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
