Repository kubernetes-sigs/image-builder, pull requests merged in 2020-01, with the labels that each got.

#116 Adding Ubuntu 20.04 LTS daily builds
  images/capi/Makefile
  images/capi/packer/ova/linux/ubuntu/http/20.04/preseed.cfg
  images/capi/packer/ova/ova-ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#115 update Photon OVA from 3.0 GA to 3.0 Rev2
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/photon.yml
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
  images/capi/packer/ova/linux/photon/http/3/ks.json
  images/capi/packer/ova/ova-photon-3.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#114 containerd: Required by cloud-config instead of cloud-final
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/boot-order.conf
Labels: approved, cncf-cla: yes, lgtm, size/XS

#117 Update to containerd 1.3.2
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#118 Add target to build photon 3 with esx
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 Photon image changes: minimal ISO, disable and mask Docker
  images/capi/packer/ova/linux/photon/http/3/ks.json
  images/capi/packer/ova/ova-photon-3.json
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#120 Add akutz to approvers in OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#123 [cluster-api Azure] Add pipeline and script to create new marketplace sku
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
  images/capi/packer/azure/ubuntu-sku-template.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#124 Add CecileRobertMichon to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#121 Clean up Makefile; standard help
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/L

#125 Minimize packages installed during Photon kickstart
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/photon.yml
  images/capi/packer/ova/linux/photon/http/3/ks.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#47 OVA: Make ubuntu preseed not rely on internet
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/debian.yml
  images/capi/ansible/roles/common/templates/etc/apt/sources.list.j2
  images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg
Labels: approved, cncf-cla: yes, lgtm, size/M

#132 Add CAPI Ubuntu image for DigitalOcean
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/digitalocean.md
  images/capi/Makefile
  images/capi/packer/digitalocean/do-default.json
  images/capi/packer/digitalocean/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#134 Make sure Ubuntu images remain immutable
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#136 Move common ansible args to one location
  images/capi/Makefile
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M
