Repository kubernetes-sigs/image-builder, pull requests merged in 2020-11, with the labels that each got.

#426 CAPI: temporarily disable Azure Ubuntu 20.04 build
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 Update Ubuntu ISO image to 18.04.5
  images/capi/packer/qemu/qemu-ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#424 CAPI: Add option to build Azure SIGs in CI script
  images/capi/Makefile
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/ci-azure-e2e.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#430 CAPZ: add creation timestamp tag for VHD packer RG
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#397 Add chrony module for supported distros and providers
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/ansible/roles/providers/tasks/debian.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#432 Azure: fix parse prow creds script
  images/capi/packer/azure/scripts/parse-prow-creds.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 legacy image-builder: Pin pyrsistent to python2 compatible version
  images/kube-deploy/imagebuilder/pkg/imagebuilder/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 Add gcp capi images
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/gcp.md
  images/capi/Makefile
  images/capi/packer/gce/gce-default.json
  images/capi/packer/gce/packer.json
  images/capi/packer/gce/ubuntu-1804.json
  images/capi/packer/gce/ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#382 Windows image configuration scripts and Azure builder
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/windows/windows.md
  images/capi/Makefile
  images/capi/ansible/windows/ansible_winrm.ps1
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/cloudbase-init/tasks/main.yml
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init-unattend.conf
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/ansible/windows/roles/debug/defaults/main.yml
  images/capi/ansible/windows/roles/debug/tasks/main.yml
  images/capi/ansible/windows/roles/kubernetes/defaults/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/nssm.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/url.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/wins.yml
  images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1
  images/capi/ansible/windows/roles/runtimes/defaults/main.yml
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
  images/capi/ansible/windows/roles/runtimes/tasks/docker_ee.yml
  images/capi/ansible/windows/roles/runtimes/tasks/main.yml
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
  images/capi/ansible/windows/roles/systemprep/defaults/main.yml
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/hack/ensure-ansible-windows.sh
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/scripts/ci-azure-e2e.sh
  images/capi/packer/azure/scripts/disable-windows-prepull.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
  images/capi/packer/azure/scripts/sysprep.ps1
  images/capi/packer/azure/windows-2004.json
  images/capi/packer/azure/windows-2019.json
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/config/windows/cloudbase-init.json
  images/capi/packer/config/windows/common.json
  images/capi/packer/config/windows/containerd.json
  images/capi/packer/config/windows/docker.json
  images/capi/packer/config/windows/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#435 Update Ubuntu20 ISO image
  images/capi/packer/qemu/qemu-ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
