Repository kubernetes-sigs/image-builder, pull requests merged in 2020-02, with the labels that each got.

#137 capi: remove NFS by default
  images/capi/ansible/roles/common/defaults/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Only disable Hyper-V protocol daemon on Ubuntu
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#139 Use a single user/pass across multiple distros
  images/capi/ansible/roles/common/tasks/photon.yml
  images/capi/hack/image-ssh.sh
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
  images/capi/packer/ova/linux/photon/http/3/ks.json
  images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg
  images/capi/packer/ova/ova-centos-7.json
  images/capi/packer/ova/ova-photon-3.json
  images/capi/packer/ova/ova-ubuntu-1804.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#141 update photon-minimal iso
  images/capi/packer/ova/linux/photon/http/3/ks.json
  images/capi/packer/ova/ova-photon-3.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#142 capi: Add separate dependency scripts
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/digitalocean.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/.gitignore
  images/capi/Makefile
  images/capi/hack/ensure-ansible.sh
  images/capi/hack/ensure-goss.sh
  images/capi/hack/ensure-jq.sh
  images/capi/hack/ensure-packer.sh
  images/capi/hack/image-tools.sh
  images/capi/hack/utils.sh
  images/capi/packer/ami/Makefile
  images/capi/packer/gce/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XL

#153 bump containerd 1.3.3
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Doc updates
  Makefile
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/digitalocean.md
  docs/book/src/capi/providers/vsphere.md
  docs/book/src/glossary.md
  hack/build-mdbook.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#152 Place user supplied var files at end of command
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#151 Add ability to inject extra packages
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/common/defaults/main.yml
  images/capi/ansible/roles/common/tasks/debian.yml
  images/capi/ansible/roles/common/tasks/photon.yml
  images/capi/ansible/roles/common/tasks/redhat.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#155 Use SHA for cri-containerd NOT upstream containerd tar.gz
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#156 capi: define containerd_url in single place
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/containerd.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#157 Revert "capi: define containerd_url in single place"
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/containerd.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/ova/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#127 imagebuilder: Add stretch images for 1.16 and 1.17
  images/kube-deploy/imagebuilder/aws-1.16-stretch.yaml
  images/kube-deploy/imagebuilder/aws-1.17-stretch.yaml
  images/kube-deploy/imagebuilder/templates/1.16-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.17-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#159 Update README and update CAPI docs
  README.md
  docs/book/src/SUMMARY.md
  docs/book/src/capi/quickstart.md
  images/capi/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 capi: Add and document support for HTTP proxy
  docs/book/src/capi/capi.md
  images/capi/ansible/playbook.yml
  images/capi/packer/config/ansible-args.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#97 enable ipv6 forwarding on instances
  images/capi/ansible/roles/common/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, size/S

#164 Update vSphere docs with SSH user and fix kubernetes test path
  docs/book/src/capi/providers/vsphere.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#166 Remove unused code, fix guestinfo data paths
  images/capi/hack/image-govc-cloudinit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#167 [capi/azure] add skuLongSummary to SKU template
  images/capi/packer/azure/ubuntu-sku-template.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
