Repository kubernetes-sigs/image-builder, pull requests merged in 2021-09, with the labels that each got.

#686 Fix Azure sigs builds
  images/capi/Makefile
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/registry.yml
  images/capi/ansible/windows/roles/runtimes/tasks/main.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/config/windows/common.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-service.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#677 provide a way for users to bring their own containerd config
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/containerd/defaults/main.yml
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/windows/roles/runtimes/defaults/main.yml
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#685 Support building Azure SIG images using custom networks
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#691 bump az cli to the latest version
  images/capi/hack/ensure-azure-cli.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#690 block traffic to 168.63.129.16 port 80 for cve-2021-27075
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#692 config: update k8s release 1.20 to use 1.20.10
  images/capi/packer/config/kubernetes.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#695 Create ssh program data if not exists on image
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#652 Add support for Azure SIG flatcar image
  images/capi/Makefile
  images/capi/ansible/python.yml
  images/capi/ansible/roles/python/defaults/main.yml
  images/capi/ansible/roles/python/tasks/flatcar.yml
  images/capi/ansible/roles/python/tasks/main.yml
  images/capi/packer/azure/flatcar.json
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#697 Bump Ubuntu 18.04 ISO to currently available ISO
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/qemu/qemu-ubuntu-1804.json
  images/capi/packer/raw/raw-ubuntu-1804.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#694 add Windows firewall rule to block 168.63.129.16:80 for cve-2021-27075
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/providers/tasks/azure.yml
  images/capi/ansible/windows/roles/providers/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#696 Checking if ssh directory exists before creating it
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm
