Repository kubernetes-sigs/image-builder, pull requests merged in 2021-11, with the labels that each got.

#729 Added virtual floppy disk feature to centos-7
  images/capi/packer/ova/centos-7.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#730 Updated to rhel7.9 and added virtual floppy disk support
  images/capi/packer/ova/rhel-7.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#638 add efi support to raw and qemu builder
  images/capi/Makefile
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-ubuntu-2004-efi.json
  images/capi/packer/raw/linux/ubuntu/http/20.04/preseed-efi.cfg
  images/capi/packer/raw/linux/ubuntu/http/base/preseed-efi.cfg
  images/capi/packer/raw/packer.json
  images/capi/packer/raw/raw-ubuntu-2004-efi.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#731 fixed kickstart file for centos-7 and rhel-7 and added centos-7 to ci…
  images/capi/packer/ova/linux/centos/http/7/ks.cfg
  images/capi/scripts/ci-ova.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#634 add goss and custom provisioner to qemu and raw
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/raw.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#733 Update capg nightly config
  images/capi/packer/gce/ci/nightly/overwrite-1-18.json
  images/capi/packer/gce/ci/nightly/overwrite-1-19.json
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/scripts/ci-gce-nightly.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#711 feat: set a default Containerd imports directory
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
Labels: size/S, cncf-cla: yes, approved, lgtm

#724 kernel values to support --protect-kernel-defaults
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/packer/goss/goss-kernel-params.yaml
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, size/XS, approved, lgtm

#728 Downgrade cloud-init. Workaround for #712
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#734 remove python2-pip from photon GOSS pkg test
  images/capi/packer/goss/goss-vars.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#732 Add networkd-dispatcher script to access NTP servers provided by DHCP
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/files/etc/networkd-dispatcher/no-carrier.d/20-chrony.j2
  images/capi/ansible/roles/providers/files/etc/networkd-dispatcher/off.d/20-chrony.j2
  images/capi/ansible/roles/providers/files/etc/networkd-dispatcher/routable.d/20-chrony.j2
  images/capi/ansible/roles/providers/files/usr/libexec/chrony-helper
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/vmware-photon.yml
  images/capi/ansible/roles/providers/tasks/vmware-ubuntu.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#735 Install apparmor-parser on photon-3
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#738 Update CAPG nightly images
  images/capi/packer/gce/ci/nightly/overwrite-1-19.json
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#744 fix al2 rpm list
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#745 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#747 images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag
  cloudbuild.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm
