Repository kubernetes-sigs/image-builder, pull requests merged in 2021-06, with the labels that each got.

#624 locked ansible base version
  images/capi/hack/ensure-ansible.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#622 add ansible_user_vars as a way to pass user defined variables to ansible
  docs/book/src/capi/capi.md
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#620 Disable GOSS inspect mode for CI tests
  images/capi/scripts/ci-azure-e2e.sh
  images/capi/scripts/ci-disable-goss-inspect.json
  images/capi/scripts/ci-gce.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#625 capg/nightly: remove check credentials
  images/capi/scripts/ci-gce-nightly.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#628 Building ova using ovftool errors out when no args are set.
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#629 Bump /tmp size on photon
  images/capi/ansible/roles/setup/tasks/photon.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#633 Prevent custom iptables rules getting overwritten by sysprep
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#635 Add more user configurable goss provisioner options
  docs/book/src/capi/goss/goss.md
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#636 Fix for multiple lines returned for Azure OS_DISK_URI
  images/capi/packer/azure/.pipelines/generate-sas.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#637 Add OWNERS for Windows Ansible roles
  OWNERS_ALIASES
  images/capi/ansible/windows/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
