Repository kubernetes-sigs/image-builder, pull requests merged in 2021-08, with the labels that each got.

#665 Update nightly CAPG jobs to the latest k8s releases and add 1.21/1.22 configs
  images/capi/packer/gce/ci/nightly/overwrite-1-18.json
  images/capi/packer/gce/ci/nightly/overwrite-1-19.json
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/scripts/ci-gce-nightly.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#671 Add option to enable .local lookups via DNS in Photon
  docs/book/src/capi/providers/vsphere.md
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/photon.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#669 Add Cilium to list of excluded nics
  images/capi/ansible/roles/providers/files/etc/vmware-tools/tools.conf
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#674 Bump k8s version to v1.20.9
  images/capi/packer/config/kubernetes.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#661 Add Windows containerd make target for Azure CI and remove SAC 2004
  images/capi/Makefile
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/windows-2019-containerd.json
Labels: sig/windows, size/M, cncf-cla: yes, approved, lgtm

#670 capi: avoid specifying containerd version for Flatcar
  images/capi/hack/image-build-flatcar.sh
  images/capi/packer/ami/flatcar.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/raw/raw-flatcar.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#681 Support building Azure images using custom networks
  docs/book/src/capi/providers/azure.md
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: size/M, cncf-cla: yes, approved, lgtm
