Repository kubernetes-sigs/image-builder, pull requests merged in 2021-01, with the labels that each got.

#415 Add `DEBUG` env var to turn on debug
  images/capi/Makefile
  images/capi/hack/boxes-flatcar.sh
  images/capi/hack/ensure-ansible-windows.sh
  images/capi/hack/ensure-ansible.sh
  images/capi/hack/ensure-azure-cli.sh
  images/capi/hack/ensure-goss.sh
  images/capi/hack/ensure-jq.sh
  images/capi/hack/ensure-packer.sh
  images/capi/hack/image-build-flatcar.sh
  images/capi/hack/image-govc-cloudinit.sh
  images/capi/hack/image-grok-latest-flatcar-version.sh
  images/capi/hack/image-post-create-config.sh
  images/capi/hack/image-ssh.sh
  images/capi/packer/azure/scripts/ci-azure-e2e.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
  images/capi/packer/files/bootstrap-flatcar.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#460 Fix QEMU image for OpenStack not to execute Flatcar specific provisioner and post-processor
  images/capi/Makefile
  images/capi/hack/image-build-flatcar.sh
  images/capi/packer/qemu/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#463 Update Windows pre-pull images and use Dec Patches
  images/capi/packer/azure/windows-2019.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#466 Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#461 capi: fix Flatcar issues with versions and AMIs
  images/capi/Makefile
  images/capi/hack/image-grok-latest-flatcar-version.sh
  images/capi/packer/ami/flatcar.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#470 add distro version & arch info to OVF Metadata
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/centos-7.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/photon-3.json
  images/capi/packer/ova/rhel-7.json
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/ova/ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#402 Windows vhd configuration - Vsphere (OVA) Builder
  docs/book/src/capi/windows/windows.md
  images/capi/Makefile
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
  images/capi/ansible/windows/roles/systemprep/defaults/main.yml
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/hack/image-build-ova.py
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/config/windows/common.json
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/ova/vsphere.json
  images/capi/packer/ova/windows-2004.json
  images/capi/packer/ova/windows-2019.json
  images/capi/packer/ova/windows/disable-network-discovery.cmd
  images/capi/packer/ova/windows/disable-winrm.ps1
  images/capi/packer/ova/windows/enable-winrm.ps1
  images/capi/packer/ova/windows/install-vm-tools.cmd
  images/capi/packer/ova/windows/pvscsi/amd64/pvscsi.cat
  images/capi/packer/ova/windows/pvscsi/amd64/pvscsi.inf
  images/capi/packer/ova/windows/pvscsi/amd64/pvscsi.sys
  images/capi/packer/ova/windows/pvscsi/amd64/txtsetup.oem
  images/capi/packer/ova/windows/pvscsi/i386/pvscsi.cat
  images/capi/packer/ova/windows/pvscsi/i386/pvscsi.inf
  images/capi/packer/ova/windows/pvscsi/i386/pvscsi.sys
  images/capi/packer/ova/windows/pvscsi/i386/txtsetup.oem
  images/capi/packer/ova/windows/sysprep.ps1
  images/capi/packer/ova/windows/windows-2004/autounattend.xml
  images/capi/packer/ova/windows/windows-2019/autounattend.xml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#469 Fix comparison for custom post processor
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#440 Fix non-working Proxy-Flags in Ansible
  images/capi/ansible/firstboot.yml
  images/capi/ansible/haproxy.yml
  images/capi/ansible/node.yml
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/http-proxy.conf
  images/capi/ansible/roles/setup/tasks/debian.yml
  images/capi/ansible/roles/setup/templates/etc/apt/apt.conf.d/90proxy
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#475 use latest so anyone building always gets the latest version
  images/capi/packer/azure/windows-2019.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#476 Fix missing comma from PR 402 causing syntax error
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#473 bump k8s to 1.18.15 (n-2) & crictl to 1.20.0
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#477 Azure: change creation timestamp tag to RFC 3339 format
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#450 Add image-promotion process to publish container images
  images/capi/Dockerfile
  images/capi/Makefile
  images/capi/cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#478 Bump mdbook to v0.4.6
  docs/book/build.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#479 fix location of cloudbuild.yaml
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#480 Fix make target for release-staging
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#467 Merge ovf templates
  images/capi/hack/image-build-ova.py
  images/capi/hack/ovf_template.xml
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#481 Fixup gcb build args
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#483 Only place required files in Docker container
  images/capi/.dockerignore
  images/capi/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#485 prepull ubuntu:focal for use with buildkit
  images/capi/Dockerfile
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#442 Adds support for Windows worker ami
  images/capi/Makefile
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init-unattend.conf
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/scripts/sysprep_prerequisites.ps1
  images/capi/packer/ami/scripts/winrm_bootstrap.txt
  images/capi/packer/ami/windows-2004.json
  images/capi/packer/ami/windows-2019.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: approved, cncf-cla: yes, lgtm, size/L
