Repository kubernetes-sigs/image-builder, pull requests merged in 2021-05, with the labels that each got.

#529 Anisble role to load addtional components
  docs/book/src/capi/capi.md
  images/capi/Makefile
  images/capi/ansible/node.yml
  images/capi/ansible/roles/load_additional_components/defaults/main.yml
  images/capi/ansible/roles/load_additional_components/tasks/executables.yml
  images/capi/ansible/roles/load_additional_components/tasks/main.yml
  images/capi/ansible/roles/load_additional_components/tasks/registry.yml
  images/capi/ansible/roles/load_additional_components/tasks/url.yml
  images/capi/packer/config/additional_components.json
  images/capi/packer/config/ansible-args.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#604 Fix apt-daily services and add GOSS tests
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#605 Added missing firmware from windows ova post processors
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS

#606 bump containerd version to v1.5.0
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#610 bump containerd version to v1.5.1
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#600 Remove Windows updates default settings to avoid automatic updates
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/S

#612 Bump base K8s version to v1.19.11
  images/capi/packer/config/kubernetes.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#614 Fix a typo: commmand
  v1/api/image.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#616 pass IB_OVFTOOL_ARGS env value if set to ovftool to build ova
  docs/book/src/capi/providers/vsphere.md
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#445 gce: add scripts for CI test and nightly builds
  images/capi/hack/ensure-boskosctl.sh
  images/capi/hack/ensure-go.sh
  images/capi/packer/gce/ci/nightly/README.md
  images/capi/packer/gce/ci/nightly/overwrite-1-18.json
  images/capi/packer/gce/ci/nightly/overwrite-1-19.json
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/scripts/ci-gce-nightly.sh
  images/capi/scripts/ci-gce.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#617 Bump containerd version to 1.5.2
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
