Repository kubernetes-sigs/image-builder, pull requests merged in 2021-07, with the labels that each got.

#642 Fix k8s.gcr.io URLs for container images
  docs/book/src/capi/container-image.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#639 Consistent cpu & ram capacity for all vsphere builders
  images/capi/packer/ova/packer-common.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#627 fixes for generating azure gen2 images
  images/capi/Makefile
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/ubuntu-1804-gen2.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#646 Update Azure "pub" tool to v0.3.2
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#647 Skip ovf/vmdk export in vsphere-iso-base builder
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#648 [OVA] [Ubuntu] Support disabling IPv6 module during boot
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/ova/ubuntu-2004-efi.json
  images/capi/packer/ova/ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#425 Add CI for OVAs
  images/capi/packer/ova/packer-node.json
  images/capi/scripts/ci-ova.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#650 Expose env var for setting container base image
  images/capi/Dockerfile
  images/capi/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#641 capg: add options to set a service account or disable the default one
  images/capi/packer/gce/ci/nightly/overwrite-1-18.json
  images/capi/packer/gce/ci/nightly/overwrite-1-19.json
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#651 Add CI script for container build
  images/capi/scripts/ci-container-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#654 Bump containerd to v1.5.3
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#623 Added windows build fixes and optimisations
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/cloudbase-init/tasks/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/nssm.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/url.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/wins.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/executables.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/registry.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/url.yml
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
  images/capi/ansible/windows/roles/runtimes/tasks/docker_ee.yml
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/hack/ensure-ansible-windows.sh
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-package.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/L

#655 capg: make capg node images available to use in another accounts
  images/capi/scripts/ci-gce-nightly.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#657 Use 1.7 ansible galaxy package for Windows
  images/capi/hack/ensure-ansible.sh
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS

#656 Use dl.k8s.io instead of hardcoded GCS URIs
  images/capi/ansible/windows/example.vars.yml
  images/capi/hack/image-new-kube.py
  images/capi/hack/serve_artifacts.go
  images/capi/packer/config/kubernetes.json
  images/kube-deploy/imagebuilder/templates/1.11-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.12-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.13-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.14-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#645 cleanup netplan files, cleanup journald
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#660 Increase Restart timeout for Windows
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS

#662 Add a script to delete unused Azure image storage
  images/capi/packer/azure/scripts/delete-unused-storage.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#663 Add a "smoke test" job to Azure pipelines
  images/capi/packer/azure/.pipelines/smoke-test.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#659 bump containerd to 1.5.4
  images/capi/packer/config/containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#666 Lower concurrency for windows goss
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS
