Repository kubernetes-sigs/image-builder, pull requests merged in 2021-12, with the labels that each got.

#746 Include additional rpms in AL2 images
  images/capi/ansible/roles/node/meta/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#749 support specifying remote_folder for packer provisioner
  images/capi/packer/azure/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#752 Fix OVA CI script to catch background errors
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#755 Disable apparmor service on photon-3
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#740 Switch base image from focal to latest
  images/capi/Dockerfile
Labels: cncf-cla: yes, sig/cluster-lifecycle, size/XS, approved, lgtm, sig/security

#756 photon: disable apparmor in kernel
  images/capi/ansible/roles/node/tasks/photon.yml
  images/capi/ansible/roles/setup/tasks/photon.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#763 fix ova-ci script to use vCenter IP directly
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#765 Add photon-3 to OVA CI list
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#759 Use dword to turn off auto updates on Windows
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/S, sig/windows, cncf-cla: yes, approved, lgtm

#750 Expand windows dynamic port range
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/S, sig/windows, cncf-cla: yes, approved, lgtm

#757 photon: Add GOSS test for apparmor disabled
  images/capi/packer/goss/goss-vars.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#769 Link to Windows docs in TOC
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#770 Bump mdBook to v0.4.14
  docs/book/build.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm
