Repository kubernetes-sigs/image-builder, pull requests merged in 2021-02, with the labels that each got.

#489 kube-deploy: Pre-populate the caches with newer dependencies
  images/kube-deploy/imagebuilder/templates/1.11-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.12-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.13-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.14-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.15-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.16-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.17-stretch.yml
  images/kube-deploy/imagebuilder/templates/1.18-stretch.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#492 Fix distro-version for ubuntu1804 OVAs
  images/capi/packer/ova/ubuntu-1804.json
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#488 images/kube-deploy: Rationalize OWNERs
  OWNERS_ALIASES
  images/kube-deploy/OWNERS
  images/kube-deploy/OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/M

#490 kube-deploy: set default instance type to m4.large
  images/kube-deploy/imagebuilder/pkg/imagebuilder/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#487 capi: make ignition capable of detecting Flatcar images
  images/capi/packer/files/bootstrap-flatcar.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#493 [capi] Azure: Adds support for custom Shared Image Gallery Image version
  images/capi/packer/azure/azure-sig.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#494 Quote CUSTOM_POST_PROCESSOR
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#491 Re-add windows_updates_categories variable
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#497 Switch Ubuntu to boot from floppy
  images/capi/packer/ova/centos-7.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/photon-3.json
  images/capi/packer/ova/rhel-7.json
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/ova/ubuntu-2004.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#499 Add image builder version to Azure metadata
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
  images/capi/packer/ova/packer-windows.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#502 docs: add proper path for make deps-qemu
  docs/book/src/capi/providers/openstack.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#501 Always install kubelet env file
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/ansible/roles/kubernetes/files/etc/sysconfig/kubelet
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/url.yml
  images/capi/ansible/roles/kubernetes/templates/etc/sysconfig/kubelet
Labels: approved, cncf-cla: yes, lgtm, size/M

#503 support adding custom ovf properties
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#507 cluster-api-provider-digitalocean: Update OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#510 No longer install cloud-initramfs-growroot Ubuntu
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#509 Use OVFTool to create OVAs
  images/capi/Makefile
  images/capi/hack/ensure-ovftool.sh
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, size/M

#512 Makes the kubernetes typed version configurable
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/packer-node.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#514 Updates `ubuntu-64` OS type to `ubuntu64Guest`
  images/capi/hack/image-build-ova.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#517 Remove inactive members from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#504 capi: fix curl and URLs to Flatcar Container Linux
  images/capi/README-flatcar.md
  images/capi/hack/image-build-flatcar.sh
  images/capi/hack/image-grok-latest-flatcar-version.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#519 Update CAPZ maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 Windows defender exclusions and missing ova generation fixes
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/ova/windows-2004.json
  images/capi/packer/ova/windows-2019.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/M

#516 Allow overriding the instance type used during the AMI build process.
  images/capi/packer/ami/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#520 Small fix to variable containerd_sha256_windows
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS
