Repository kubernetes-sigs/image-builder, pull requests merged in 2022-09, with the labels that each got.

#963 Remove outdated Flatcar-specific README
  images/capi/README-flatcar.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#964 Add timeout and retry when installing baseline dependencies.
  images/capi/ansible/roles/setup/tasks/debian.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#965 Bump k8s version to 1.23.10-0
  docs/book/src/capi/capi.md
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#970 Fix Flatcar detection in node role
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/setup/defaults/main.yml
  images/capi/ansible/roles/setup/tasks/bootstrap-flatcar.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#973 Update gce nightly build images
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#974 docs: expanding Azure documentation with optional environment variable GALLERY_NAME
  docs/book/src/capi/providers/azure.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#975 Pin openssl and crypto packages to known working versions
  images/capi/ansible/roles/providers/tasks/debian.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#929 images/capi/packer/azure: small SIG related improvements and fixes
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#976 Updated kubernetes-cni .deb to v1.1.1
  images/capi/packer/config/cni.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#966 Support setting oem_id for Flatcar QEMU images
  images/capi/ansible/roles/sysprep/tasks/flatcar.yml
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-flatcar.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#971 Update references following Flatcar GitHub org rename
  images/capi/hack/boxes-flatcar.sh
  images/capi/hack/ensure-ct.sh
  images/capi/hack/image-build-flatcar.sh
  images/capi/hack/image-grok-latest-flatcar-version.sh
  images/capi/packer/files/flatcar/README.md
  images/capi/packer/goss/goss-service.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#979 Add sbueringer to ClusterAPI maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#977 remove 1.21 job and add 1.25
  images/capi/scripts/ci-gce-nightly.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#981 feat: add `base_image_ocid` param for CAPI Oracle Cloud provider
  docs/book/src/capi/providers/oci.md
  images/capi/packer/oci/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#983 Install curl on Photon builds
  images/capi/ansible/roles/node/defaults/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#982 initial checkin of nutanix image-builder
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/nutanix.md
  images/capi/Makefile
  images/capi/packer/nutanix/config.pkr.hcl
  images/capi/packer/nutanix/nutanix.json
  images/capi/packer/nutanix/packer.json
  images/capi/packer/nutanix/ubuntu-2004.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#847 Adding support for Kubevirt capi images
  images/capi/Makefile
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/kubevirt-Dockerfile
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/scripts/build_kubevirt_image.sh
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#988 Update AMI owner ID for centOS AMIs
  images/capi/packer/ami/centos-7.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
