Repository kubernetes-sigs/image-builder, pull requests merged in 2022-12, with the labels that each got.

#1027 Upgrade pip3 to latest to fix awscli installation failure
  images/capi/ansible/roles/providers/tasks/aws.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1019 update capg images to use latest k8s releases
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1024 Refresh OWNERs file
  OWNERS
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, approved, lgtm

#1023 Adding http port max and min parameters
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1025 Add AverageMarcus as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1028 images/capi/packer/azure: allow building images from various SIG images
  docs/book/src/capi/providers/azure.md
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1031 Enable HNS and WCIFS fixes for WS2019
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: sig/windows, size/M, cncf-cla: yes, approved, lgtm

#947 updating dynamic port range for windows to address some collisions
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#1030 Nutanix: Allow output image override if already exists
  images/capi/packer/nutanix/nutanix.json
  images/capi/packer/nutanix/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#994 Added Ubuntu 22.04 builds for AWS and GCP
  images/capi/Makefile
  images/capi/packer/ami/ubuntu-2204.json
  images/capi/packer/gce/ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1029 Migrate from osc to outscale and remove image centos7
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/outscale.yml
  images/capi/packer/outscale/centos-7.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1034 Update Rocky Linux urls and checksums to 8.7
  images/capi/packer/ova/rockylinux-8.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1033 add support for ansible_user_vars in nutanix
  images/capi/packer/nutanix/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1036 Update OWNERS_ALIASES for Azure
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1005 Add pipeline test job for Azure VHDs
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/generate-sas.yaml
  images/capi/packer/azure/.pipelines/stages.yaml
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/.pipelines/vhd-publishing-info.yaml
  images/capi/packer/azure/scripts/ensure-kustomize.sh
  images/capi/packer/azure/scripts/init-vhd.sh
  images/capi/packer/azure/scripts/test-templates/linux/kustomization.yaml
  images/capi/packer/azure/scripts/test-templates/patches/azuremachinetemplate-controlplane.yaml
  images/capi/packer/azure/scripts/test-templates/patches/azuremachinetemplate-windows.yaml
  images/capi/packer/azure/scripts/test-templates/patches/azuremachinetemplate-workload.yaml
  images/capi/packer/azure/scripts/test-templates/patches/kubeadmcontrolplane-windows.yaml
  images/capi/packer/azure/scripts/test-templates/patches/machinedeployment-windows.yaml
  images/capi/packer/azure/scripts/test-templates/windows/kustomization.yaml
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1038 containerd: Update to v1.6.14
  images/capi/packer/config/containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1035 images/capi: improve out-of-the-box compatibility with OpenSSH versions 8.8+ and 9.0+
  images/capi/Makefile
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/gce/packer.json
  images/capi/packer/oci/packer.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/powervs/packer.json
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1037 add containerd-wasm-shims to enable Wasm / WASI workloads
  images/capi/Makefile
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/packer/azure/azure-config.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/wasm-shims.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1041 Fix Makefiles and update image-builder
  Makefile
  v1/Makefile
  v1/go.mod
  v1/go.sum
Labels: size/L, cncf-cla: yes, approved, lgtm

#1040 Update mdBook and fix darwin install
  docs/book/build.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1042 Update capg nightly build images
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
Labels: size/M, cncf-cla: yes, approved, lgtm
