Repository kubernetes-sigs/image-builder, pull requests merged in 2022-01, with the labels that each got.

#768 ensure goss installation for the qemu and raw targets
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#772 Use python3 for windows build
  images/capi/hack/windows-ova-unattend.py
Labels: ok-to-test, sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#774 Always install Galaxy collections
  images/capi/hack/ensure-ansible.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#721 Support for RHEL/Rocky 8 image for qemu
  images/capi/Makefile
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/ova/linux/centos/http/8/ks.cfg
  images/capi/packer/ova/linux/rockylinux/http/8/ks.cfg
  images/capi/packer/qemu/qemu-rhel-8.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#762 Use nssm for kubelet log rotation on Windows
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/nssm.yml
  images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/packer-windows.json
Labels: sig/windows, size/M, cncf-cla: yes, approved, lgtm

#751 Make debug_tools configurable
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/config/windows/common.json
  images/capi/packer/ova/packer-windows.json
Labels: ok-to-test, sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#777 Refresh OWNERs files
  OWNERS
  OWNERS_ALIASES
Labels: size/M, cncf-cla: yes, approved, lgtm

#754 Add support for OCI Images
  docs/book/src/SUMMARY.md
  docs/book/src/capi/providers/oci.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/oci.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/oci/oracle-linux-8.json
  images/capi/packer/oci/packer.json
  images/capi/packer/oci/ubuntu-1804.json
  images/capi/packer/oci/ubuntu-2004.json
  images/capi/scripts/ci-packer-validate.sh
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#778 Fix target argument in Makefile substitution command
  images/capi/Makefile
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#783 Only provide dockershim flags with docker below 1.24
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1
Labels: sig/windows, size/M, cncf-cla: yes, approved, lgtm

#699 Adding virtualbox local build for local environment base box
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/virtualbox.md
  docs/book/src/glossary.md
  images/capi/Makefile
  images/capi/packer/vbox/OWNERS
  images/capi/packer/vbox/packer-common.json
  images/capi/packer/vbox/packer-windows.json
  images/capi/packer/vbox/vagrantfile-windows_2019.template
  images/capi/packer/vbox/windows-2019.json
  images/capi/packer/vbox/windows/enable-winrm.ps1
  images/capi/packer/vbox/windows/sysprep.ps1
  images/capi/packer/vbox/windows/windows-2019/autounattend.xml
Labels: cncf-cla: yes, size/XL, approved, lgtm

#742 Move VMware tools installation to specialize phase of Windows install
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/ova/windows/install-vm-tools.cmd
  images/capi/packer/ova/windows/windows-2004/autounattend.xml
  images/capi/packer/ova/windows/windows-2019/autounattend.xml
  images/capi/packer/ova/windows/windows-2022/autounattend.xml
Labels: ok-to-test, sig/windows, size/M, cncf-cla: yes, approved, lgtm

#776 Bump Containerd to 1.5.9
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#787 disable WS 2022 from ci
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#786 fix cloud-init install & downgrade ordering
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#788 Removing unecessary default vagrant credentials
  images/capi/packer/vbox/vagrantfile-windows_2019.template
Labels: cncf-cla: yes, size/XS, approved, lgtm

#789 Use updated OVA CI credentials.
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#771 Remove vSphere ESX builder for node & haproxy images
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/packer/ova/esx.json
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#790 Add Windows Server 2022 back to CI
  images/capi/Makefile
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/windows-2022-containerd.json
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#791 Update docs to use latest image-builder container v0.1.11
  docs/book/src/capi/container-image.md
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm
