Repository kubernetes-sigs/image-builder, pull requests merged in 2022-04, with the labels that each got.

#843 fix: windows goss wrong provider on AWS
  images/capi/packer/ami/packer-windows.json
Labels: ok-to-test, sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#850 Add ability to supply global pip config file
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/setup/defaults/main.yml
  images/capi/ansible/roles/setup/tasks/main.yml
  images/capi/ansible/roles/sysprep/defaults/main.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#820 Make the CLI compile
  v1/Makefile
  v1/cmd/build.go
  v1/go.mod
  v1/go.sum
  v1/pkg/distros/distro.go
  v1/pkg/resources/defaults.yml
  v1/pkg/resources/distros/amazonLinux.yml
  v1/pkg/resources/distros/centos.yml
  v1/pkg/resources/distros/debian.yml
  v1/pkg/resources/distros/ubuntu.yml
  v1/pkg/resources/ks.cfg
  v1/pkg/resources/preseed.cfg
Labels: size/L, cncf-cla: yes, approved, lgtm

#827 Make Flatcar build process more generic
  images/capi/ansible/roles/setup/tasks/flatcar.yml
  images/capi/packer/ami/flatcar.json
  images/capi/packer/azure/flatcar.json
  images/capi/packer/goss/goss-flatcar.yaml
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#852 Add missing comma in vsphere.md
  docs/book/src/capi/providers/vsphere.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#856 Absolute in Windows kubelet don't work < 1.23
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#813 Modify permission of SSH folder
  images/capi/ansible/windows/roles/systemprep/tasks/ssh-archive.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/config/windows/common.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/vbox/packer-windows.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#863 Fix building Flatcar images for Flatcar stable releases after 3139.2.0
  images/capi/ansible/python.yml
  images/capi/ansible/roles/python/tasks/main.yml
  images/capi/ansible/roles/setup/tasks/bootstrap-flatcar.yml
  images/capi/ansible/roles/setup/tasks/flatcar.yml
  images/capi/ansible/roles/setup/tasks/main.yml
  images/capi/packer/azure/flatcar.json
  images/capi/packer/azure/packer.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#829 Fix QEMU Flatcar build
  images/capi/Makefile
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-centos-7.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#869 Remove deprecated HAProxy OVA
  images/capi/Makefile
  images/capi/ansible/haproxy.yml
  images/capi/ansible/roles/haproxy/defaults/main.yml
  images/capi/ansible/roles/haproxy/files/etc/haproxy/haproxy.cfg
  images/capi/ansible/roles/haproxy/files/etc/systemd/system/haproxy.service.d/cloud-init.conf
  images/capi/ansible/roles/haproxy/meta/main.yml
  images/capi/ansible/roles/haproxy/tasks/main.yml
  images/capi/hack/image-build-ova.py
  images/capi/hack/image-upload.py
  images/capi/packer/ova/packer-haproxy.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: cncf-cla: yes, size/XL, approved, lgtm

#872 Separate OVA CI logs into separate files
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm
