Repository kubernetes-sigs/image-builder, pull requests merged in 2022-10, with the labels that each got.

#990 Update Azure pub tool to v0.3.3
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#989 Remove old build targets from Azure test matrix
  images/capi/azure_targets.sh
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#961 Add Ubuntu 22.04 LTS for Azure
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/ubuntu-2204-gen2.json
  images/capi/packer/azure/ubuntu-2204.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#996 Bump GOSS and packer-plugin-powervs versions
  images/capi/hack/ensure-goss.sh
  images/capi/hack/ensure-powervs.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#999 Update nssm default download location
  images/capi/packer/config/windows/common.json
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#1000 Ensure Azure storage accounts are private
  images/capi/packer/azure/scripts/delete-unused-storage.sh
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1004 Bump packer-provisioner-goss to 3.1.4
  images/capi/hack/ensure-goss.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm
