Repository kubernetes-sigs/image-builder, pull requests merged in 2022-06, with the labels that each got.

#909 build 1.21.13/1.22.10/1.23.7/1.24.1 nightly images
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#915 update nightly gce images
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#918 bump base template for photon-3 OVA ci
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#902 Add RockyLinux 8 to OVA CI
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#914 capi: remove pki Ansible role
  images/capi/ansible/roles/pki/files/usr/local/bin/new-ca.sh
  images/capi/ansible/roles/pki/files/usr/local/bin/new-cert.sh
  images/capi/ansible/roles/pki/tasks/main.yml
Labels: size/L, cncf-cla: yes, approved, lgtm

#923 images/capi/ansible/roles/node: fix Flatcar builds
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/files/usr/local/bin/etcd-network-tuning.sh
  images/capi/ansible/roles/node/tasks/amazonLinux2.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/node/templates/etc/udev/rules.d/90-etcd-tuning.rules
Labels: size/S, cncf-cla: yes, approved, lgtm

#911 Pause before and retry Azure ansible provisioner
  images/capi/packer/azure/packer-windows.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#913 Don't recreate Azure resource group if it already exists
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#926 Sync Azure maintainers with CAPZ project
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#920 prevent package upgrades on node images
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#925 use kubernetes_semver in AMI naming
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#895 Add Flatcar bootstrap Ignition files
  images/capi/Makefile
  images/capi/hack/ensure-ct.sh
  images/capi/packer/ami/packer.json
  images/capi/packer/files/flatcar/README.md
  images/capi/packer/files/flatcar/clc/bootstrap.yaml
  images/capi/packer/files/flatcar/ignition/bootstrap.json
  images/capi/packer/files/flatcar/scripts/bootstrap-flatcar.sh
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/raw/packer.json
Labels: size/L, cncf-cla: yes, approved, lgtm
