Repository kubernetes-sigs/image-builder, pull requests merged in 2022-11, with the labels that each got.

#1006 Add Ubuntu 22.04 LTS build support to CAPI OCI provider
  docs/book/src/capi/providers/oci.md
  images/capi/Makefile
  images/capi/packer/oci/ubuntu-2204.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1001 Disable pip version check
  images/capi/hack/ensure-ansible-windows.sh
  images/capi/hack/ensure-ansible.sh
  images/capi/hack/ensure-azure-cli.sh
  images/capi/hack/utils.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1007 Added qemu/kubevirt support for multiple Kubernetes versions
  images/capi/packer/qemu/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#998 Ensure ubuntu install uses console=ttyS0 kernel args
  images/capi/packer/ova/linux/ubuntu/http/base/preseed.cfg
  images/capi/packer/raw/linux/ubuntu/http/base/preseed.cfg
Labels: cncf-cla: yes, size/XS, approved, lgtm

#912 Improve bootstrap-flatcar.sh
  images/capi/packer/files/flatcar/scripts/bootstrap-flatcar.sh
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1020 Add packer plugin install for oracle
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1021 Set FLATCAR_VERSION to latest available in Azure CI
  images/capi/scripts/ci-azure-e2e.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
