Repository kubernetes-sigs/image-builder, pull requests merged in 2022-07, with the labels that each got.

#917 Add option for custom pre/post roles
  docs/book/src/capi/capi.md
  images/capi/ansible/firstboot.yml
  images/capi/ansible/node.yml
  images/capi/ansible/windows/node_windows.yml
  images/capi/hack/image-build-ova.py
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/packer-windows.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#928 Adding containerd_timeout variable for Windows
  images/capi/ansible/windows/roles/runtimes/tasks/containerd.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#933 Fix OVA post-processor
  images/capi/hack/ovf_template.xml
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#931 Example definitions under Azure guide flipped
  docs/book/src/capi/providers/azure.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#927 Hold packages before reverting custom repo configs
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
Labels: size/M, cncf-cla: yes, approved, lgtm
