Repository kubernetes-sigs/image-builder, pull requests merged in 2022-05, with the labels that each got.

#875 Use com2 serial port for logging on Azure
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/goss/goss-vars.yaml
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#877 unpin WS 2022 image
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/packer/azure/windows-2022-containerd.json
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#874 ami: Use cloud-init only on supported distros
  images/capi/packer/ami/flatcar.json
  images/capi/packer/ami/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#871 feat: expose security group and ssh variables in capi packer ami
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#880 Fix QEMU boot_media_path overrides
  images/capi/packer/qemu/qemu-centos-7.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#868 Set transparent huge pages to madvise
  images/capi/ansible/roles/firstboot/tasks/photon.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#883 Simplify conditional in Flatcar provisioner
  images/capi/packer/ami/packer.json
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#886 Enabling custom roles instructions
  docs/book/src/capi/capi.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#887 Update gce images
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/scripts/ci-gce-nightly.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#889 ova: Remove downgrade of cloud-init, no longer install guestinfo datasource when not needed
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/vmware-photon.yml
  images/capi/ansible/roles/providers/tasks/vmware-redhat.yml
  images/capi/ansible/roles/providers/tasks/vmware-ubuntu.yml
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: size/L, cncf-cla: yes, approved, lgtm

#888 Fix regression in Flatcar provisioner
  images/capi/packer/ami/packer.json
  images/capi/packer/files/bootstrap-flatcar.sh
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#878 Update Azure scripts for new naming scheme
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#891 Bump k8s version to v1.22.9
  docs/book/src/capi/capi.md
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#896 Remove KUBERNETES_VERSION from Azure SKU template
  images/capi/packer/azure/sku-template.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#893 qemu,raw: Mask sshd during bootstrap
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/raw/raw-flatcar.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#834 flatcar Azure gen2 images
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/flatcar-gen2.json
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#900 Modify cloud.cfg to preserve hostname on reboot for OVAs
  images/capi/ansible/roles/providers/files/etc/systemd/system/modify-cloud-init-cfg.service
  images/capi/ansible/roles/providers/files/usr/local/bin/modify-cloud-init-cfg.sh
  images/capi/ansible/roles/providers/tasks/vmware.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#901 tune node images for max etcd network performance
  images/capi/ansible/roles/node/files/etc/udev/rules.d/90-etcd-tuning.rules
  images/capi/ansible/roles/node/files/usr/local/bin/etcd-network-tuning.sh
  images/capi/ansible/roles/node/tasks/main.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#899 Update to Rocky Linux 8.6
  images/capi/packer/ova/rockylinux-8.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
