Repository kubernetes-sigs/image-builder, pull requests merged in 2022-03, with the labels that each got.

#801 Build RockyLinux-8 AMI
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/packer/ami/rockylinux-8.json
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#818 Fix hyperlink in Azure docs
  docs/book/src/capi/providers/azure.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#793 Azure: archive storage accounts used for reference images
  images/capi/packer/azure/scripts/delete-unused-storage.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#822 containerd: update to v1.6.1
  images/capi/packer/config/containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#831 Bump OVA template version used for Photon CI
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#824 Update VMware GuestInfo DS to v1.4.1
  images/capi/packer/ova/packer-common.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#823 Install nfs-common package for Azure image
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#764 Fix the location of the containerd state/root folders for Windows
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
  images/capi/packer/goss/goss-command.yaml
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#832 Windows: remove admin user when creating custom user
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#836 doc: add OCI to CAPI provider list
  docs/book/src/capi/capi.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#837 Make al-2 images immutable by disabling security updates on boot.
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/amazonLinux2.yml
  images/capi/packer/ami/packer.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#826 feat: allow overriding volume_type and throughput
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
Labels: size/S, ok-to-test, sig/windows, cncf-cla: yes, approved, lgtm

#835 Install Azure Key Vault gMSA plugin if configured
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/gmsa/defaults/main.yml
  images/capi/ansible/windows/roles/gmsa/files/install-gmsa-keyvault-plugin.ps1
  images/capi/ansible/windows/roles/gmsa/tasks/gmsa_keyvault.yml
  images/capi/ansible/windows/roles/gmsa/tasks/main.yml
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/goss/goss-command.yaml
Labels: size/L, sig/windows, cncf-cla: yes, approved, lgtm

#825 fix(windows): custom role arguments passing
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: ok-to-test, sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#839 fix(AWS): add SSH key to windows images
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/goss/goss-vars.yaml
Labels: ok-to-test, sig/windows, cncf-cla: yes, size/XS, approved, lgtm
