Repository kubernetes-sigs/image-builder, pull requests merged in 2022-02, with the labels that each got.

#795 update k8s releases and add 1.23 to be built in the job
  images/capi/packer/gce/ci/nightly/overwrite-1-20.json
  images/capi/packer/gce/ci/nightly/overwrite-1-21.json
  images/capi/packer/gce/ci/nightly/overwrite-1-22.json
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/scripts/ci-gce-nightly.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#796 Fix CentOS build for OVAs by upgrading pip
  images/capi/ansible/roles/providers/tasks/vmware.yml
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#792 Updating links to Rocky Linux 8.5
  images/capi/packer/ova/linux/rockylinux/http/8/ks.cfg
  images/capi/packer/ova/rockylinux-8.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#797 enable ubuntu 20.04 for gce
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#802 containerd: update to 1.6.0
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#761 Fix failure observed during adding additional registry images
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/url.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#758 Remove unwanted boot-order from the containerd service
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/boot-order.conf
Labels: size/S, cncf-cla: yes, approved, lgtm

#807 crictl and k8s updates
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#799 Add option to compress capi/qemu images
  images/capi/packer/qemu/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#812 allow user to specify temporary_security_group_source_cidrs
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#805 Add containerd source client header for CAPZ
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/ansible/windows/roles/runtimes/templates/config.toml
Labels: size/S, cncf-cla: yes, approved, lgtm

#804 Add skip_create_ami flag to amazon-ebs builder
  docs/book/src/capi/providers/aws.md
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/ami/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#816 Remove burrito code from image-builder
  images/capi/hack/README.md
  images/capi/hack/serve_artifacts.go
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#736 Separate Azure CI logs
  images/capi/.dockerignore
  images/capi/Dockerfile
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#785 Replacing \var\lib\kubelet path to \etc\kubernetes
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm
