Repository kubernetes-sigs/image-builder, pull requests merged in 2023-11, with the labels that each got.

#1340 Add Goss output files to .gitignore
  images/capi/.gitignore
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1337 Set Flatcar OS_TYPE as other4xLinux64Guest
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/flatcar.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1338 Bump ansible-lint to v6.21.1
  images/capi/.ansible-lint-ignore
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/firstboot/meta/main.yml
  images/capi/ansible/roles/kubernetes/tasks/photon.yml
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/python/tasks/flatcar.yml
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
  images/capi/hack/ensure-ansible-lint.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1344 Update docs after v0.1.21 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1317 Flatcar: Use OS default volume/exec symlink
  images/capi/ansible/roles/setup/files/etc/systemd/system/usr-libexec.mount
  images/capi/ansible/roles/setup/tasks/flatcar.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1347 Restore /etc/resolv.conf symlink on Flatcar CAPI Azure images
  images/capi/packer/azure/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1348 Install linux-modules-extra-azure to work around CIFS bug
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: size/S, cncf-cla: yes, approved, lgtm
