Repository kubernetes-sigs/image-builder, pull requests merged in 2023-12, with the labels that each got.

#1352 made gridd and license optional
  images/capi/ansible/roles/nvidia/README.md
  images/capi/ansible/roles/nvidia/tasks/main.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1357 Bump ansible-core to v2.16.1
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1358 Bump packer to v1.9.5
  images/capi/hack/ensure-packer.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1345 `make lint` runs shellcheck on shell scripts as well
  images/capi/Makefile
  images/capi/hack/ensure-shellcheck.sh
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1356 Revert "Install linux-modules-extra-azure to work around CIFS bug"
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1364 Remove containerd-wasm-shim tarballs after installing
  images/capi/ansible/roles/containerd/tasks/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1362 Add QEMU Support for CentOS 9 Stream
  images/capi/Makefile
  images/capi/packer/qemu/linux/centos/http/9/ks.cfg
  images/capi/packer/qemu/qemu-centos-9.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1366 Fix cloud-init feature flags issue for redhat 9 (issue #1235)
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm
