Repository kubernetes-sigs/image-builder, pull requests merged in 2023-07, with the labels that each got.

#1199 Add fallback for gcloud command
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1216 Make containerd unpack location configurable
  images/capi/ansible/roles/containerd/tasks/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1217 Use ssh-extra-args param
  images/capi/packer/powervs/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1192 Add support for Mariner Linux on Azure
  docs/book/src/capi/goss/goss.md
  images/capi/Makefile
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/limit-nofile.conf
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/tasks/mariner.yml
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/ansible/roles/providers/tasks/mariner.yml
  images/capi/ansible/roles/setup/tasks/main.yml
  images/capi/ansible/roles/setup/tasks/mariner.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/mariner.yml
  images/capi/azure_targets.sh
  images/capi/packer/azure/mariner-2-gen2.json
  images/capi/packer/azure/mariner-2.json
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/kubernetes.json
  images/capi/packer/goss/goss-vars.yaml
Labels: size/L, cncf-cla: yes, approved, lgtm

#1220 Updated wasm-shims to 0.7.0, added support for wws
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/packer/azure/azure-config.json
  images/capi/packer/config/wasm-shims.json
  images/capi/packer/goss/goss-command.yaml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1215 Add fallback for tools that don't have darwin/arm64 binaries
  images/capi/hack/ensure-goss.sh
  images/capi/hack/utils.sh
  images/capi/packer/azure/scripts/ensure-kustomize.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1219 Bump packer to 1.9.1
  images/capi/Makefile
  images/capi/hack/ensure-packer.sh
  images/capi/packer/openstack/config.pkr.hcl
Labels: size/S, cncf-cla: yes, approved, lgtm

#1171 Feature flag for containerd auditd rules
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/packer/config/ansible-args.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1150 Disable Flatcar updates during image creation
  images/capi/Makefile
  images/capi/packer/ami/flatcar.json
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/flatcar-gen2.json
  images/capi/packer/azure/flatcar.json
  images/capi/packer/azure/packer.json
  images/capi/packer/files/flatcar/clc/bootstrap.yaml
  images/capi/packer/files/flatcar/ignition/bootstrap.json
  images/capi/packer/ova/flatcar.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/raw/raw-flatcar.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1225 Add chrony hook for Openstack
  images/capi/ansible/roles/providers/tasks/openstack.yml
  images/capi/ansible/roles/providers/tasks/qemu.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1224 images/capi/packer/config/ansible-args.json: remove ssh-rsa workaround
  images/capi/Makefile
  images/capi/packer/config.pkr.hcl
  images/capi/packer/config/ansible-args.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1222 Allow customizable kubernetes architecture
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/kubernetes.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1201 Remove VMWare open-vm-tools from qemu images
  images/capi/packer/qemu/linux
  images/capi/packer/qemu/linux/centos/http/7/ks.cfg
  images/capi/packer/qemu/linux/centos/http/8/ks.cfg
  images/capi/packer/qemu/linux/photon/http/3/ks.json
  images/capi/packer/qemu/linux/photon/http/4
  images/capi/packer/qemu/linux/rhel
  images/capi/packer/qemu/linux/rockylinux/http/8/ks.cfg
  images/capi/packer/qemu/linux/ubuntu/http/18.04/preseed.cfg
  images/capi/packer/qemu/linux/ubuntu/http/20.04/preseed-efi.cfg
  images/capi/packer/qemu/linux/ubuntu/http/20.04/preseed.cfg
  images/capi/packer/qemu/linux/ubuntu/http/22.04.efi/meta-data
  images/capi/packer/qemu/linux/ubuntu/http/22.04.efi/user-data
  images/capi/packer/qemu/linux/ubuntu/http/22.04/meta-data
  images/capi/packer/qemu/linux/ubuntu/http/22.04/user-data
  images/capi/packer/qemu/linux/ubuntu/http/base/preseed-efi.cfg
  images/capi/packer/qemu/linux/ubuntu/http/base/preseed.cfg
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1223 fix: making nvidia standalone due to conflicts with load_additional_components
  images/capi/ansible/roles/nvidia/README.md
  images/capi/ansible/roles/nvidia/tasks/main.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1229 adds cdrom_type and http_ip to packer node variables.
  images/capi/packer/ova/packer-node.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1230 add photon-5 support
  images/capi/Makefile
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/linux/photon/http/5/ks.json
  images/capi/packer/ova/photon-5.json
  images/capi/scripts/ci-ova.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#1231 OVA CI Cleanup
  images/capi/scripts/ci-ova.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1141 Fixed RHEL image ssh issue: Updated CLI and feature override
  images/capi/ansible/roles/providers/files/usr/lib/python3/site-packages/cloudinit/feature_overrides.py
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/ansible/roles/providers/tasks/awscliv2.yml
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1233 qemu: configure networkd-dispatcher only if ansible_os_family is Debian
  images/capi/ansible/roles/providers/tasks/openstack.yml
  images/capi/ansible/roles/providers/tasks/qemu.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1237 Adding ip_settle_timeout to detect the IP change
  images/capi/packer/ova/packer-node.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1234 Nutanix - align debug tools between Ubuntu and RedHat
  images/capi/ansible/roles/providers/tasks/nutanix-redhat.yml
  images/capi/ansible/roles/providers/tasks/nutanix-ubuntu.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1238 Update CAPV maintainers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1239 Upgraded containerd_wasm_shims_version to v0.8.0
  images/capi/packer/config/wasm-shims.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
