Repository kubernetes-sigs/image-builder, pull requests merged in 2023-01, with the labels that each got.

#1043 update default k8s release and cri-tools
  docs/book/src/capi/capi.md
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1045 feat: Add Oracle Linux 9 build support to CAPI OCI provider
  docs/book/src/capi/providers/oci.md
  images/capi/Makefile
  images/capi/packer/oci/oracle-linux-9.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1049 Unpin azure-cli to always install the latest
  images/capi/hack/ensure-azure-cli.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1052 Update book Makefile
  docs/book/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1053 bump containerd to 1.16.15 and packer to 1.8.5
  images/capi/hack/ensure-packer.sh
  images/capi/packer/config/containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1054 capi/packer/qemu: Pass oem_id value to ansible
  images/capi/packer/qemu/qemu-flatcar.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1057 Add `use_internal_ip` to gce's packer.json
  images/capi/packer/gce/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1056 Storage Account should default to AZURE_LOCATION
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1059 Add photon-4 OVA support
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/linux/photon/http/4
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/photon-4.json
  images/capi/scripts/ci-ova.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#1060 Update kubernetes-cni .deb to v1.2.0
  images/capi/ansible/roles/kubernetes/tasks/debian.yml
  images/capi/packer/config/cni.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1061 Add support to build RHEL-8 AMIs on AWS
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/ami/rhel-8.json
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1062 Support building RHEL-8 Azure VHD and SIG Images
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/centos-7-gen2.json
  images/capi/packer/azure/centos-7.json
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/rhel-8.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1051 Add support for Windows 2019/2022 to OCI capi provider image builder
  docs/book/src/capi/providers/oci.md
  images/capi/Makefile
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/nutanix/packer-windows.json
  images/capi/packer/oci/packer-windows.json
  images/capi/packer/oci/scripts/attach_secondary_vnic.ps1
  images/capi/packer/oci/scripts/enable_second_nic.ps1
  images/capi/packer/oci/scripts/set_bootstrap.sh
  images/capi/packer/oci/scripts/sysprep.ps1
  images/capi/packer/oci/scripts/unset_bootstrap.sh
  images/capi/packer/oci/scripts/winrm_bootstrap_template.txt
  images/capi/packer/oci/windows-2019.json
  images/capi/packer/oci/windows-2022.json
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/vbox/packer-windows.json
Labels: size/L, cncf-cla: yes, approved, lgtm
