Repository kubernetes-sigs/image-builder, pull requests merged in 2023-08, with the labels that each got.

#1243 Adding the destroy field to vsphere-clone and vsphere-iso builders
  images/capi/packer/ova/packer-node.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1241 Update containerd to 1.6.22
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1245 Bump Packer to v1.9.2
  images/capi/hack/ensure-packer.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1248 Update docs for v0.1.18 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1250 CAPC: Remove ConfigDrive from cloud-init datasource_list in cloudstack images
  images/capi/ansible/roles/providers/tasks/cloudstack.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1253 use "github.com/hashicorp/azure" version "<2.0.0"
  images/capi/packer/azure/config.pkr.hcl
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1251 Update qemu ubuntu-2204 image to use latest
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1264 Remove Ubuntu 18.04 from all providers
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/ami/packer.json
  images/capi/packer/ami/ubuntu-1804.json
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/create-disk-version.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/.pipelines/stages.yaml
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
  images/capi/packer/azure/ubuntu-1804-gen2.json
  images/capi/packer/azure/ubuntu-1804.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/digitalocean/ubuntu-1804.json
  images/capi/packer/gce/packer.json
  images/capi/packer/oci/packer.json
  images/capi/packer/oci/ubuntu-1804.json
  images/capi/packer/outscale/packer.json
  images/capi/packer/ova/ubuntu-1804.json
  images/capi/packer/qemu/qemu-ubuntu-1804.json
  images/capi/packer/raw/raw-ubuntu-1804.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1265 Bump default k8s to 1.26.7
  docs/book/src/capi/capi.md
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1268 Bump ansible to v2.15.3
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1269 Bump Packer to v1.9.4
  images/capi/hack/ensure-packer.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1273 Clean up more references to Ubuntu 18.04
  docs/book/src/capi/providers/openstack.md
  docs/book/src/capi/providers/raw.md
Labels: kind/documentation, size/S, cncf-cla: yes, approved, lgtm

#1271 Remove unsupported Windows 2004 SAC release
  images/capi/Makefile
  images/capi/ansible/windows/roles/runtimes/defaults/main.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/hack/image-build-ova.py
  images/capi/packer/ami/windows-2004.json
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/create-disk-version.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/windows-2004.json
  images/capi/packer/ova/windows-2004.json
  images/capi/packer/ova/windows/windows-2004/autounattend.xml
Labels: size/L, cncf-cla: yes, approved, lgtm

#1274 update windows reference template
  images/capi/packer/azure/scripts/test-templates/windows/kustomization.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1270 Update docker image base to Ubuntu jammy
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1277 Remove ubuntu-1804 from DO docs
  docs/book/src/capi/providers/digitalocean.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1275 Bump ansible to v2.15.3
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1279 Remove inline provisioner for GCE Ubuntu
  images/capi/packer/gce/packer.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1122 Adding support for qemu-ubuntu-2204-efi.
  docs/book/src/capi/providers/raw.md
  images/capi/Makefile
  images/capi/packer/qemu/linux/ubuntu/http/22.04.efi.qemu/meta-data
  images/capi/packer/qemu/linux/ubuntu/http/22.04.efi.qemu/user-data
  images/capi/packer/qemu/qemu-ubuntu-2204-efi.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1276 Update containerd to 1.6.23
  images/capi/packer/config/containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1170 Support for CAPI images on Hetzner Cloud
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/hcloud.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/hcloud/OWNERS
  images/capi/packer/hcloud/centos-7.json
  images/capi/packer/hcloud/config.pkr.hcl
  images/capi/packer/hcloud/flatcar.json
  images/capi/packer/hcloud/hcloud-config.json
  images/capi/packer/hcloud/packer-flatcar.json
  images/capi/packer/hcloud/packer.json
  images/capi/packer/hcloud/rockylinux-8.json
  images/capi/packer/hcloud/rockylinux-9.json
  images/capi/packer/hcloud/scripts/install-flatcar.sh
  images/capi/packer/hcloud/ubuntu-2004.json
  images/capi/packer/hcloud/ubuntu-2204.json
  images/capi/scripts/ci-packer-validate.sh
Labels: ok-to-test, cncf-cla: yes, size/XL, approved, lgtm

#1284 Azure: Remove quotes from tags in test VHD script
  images/capi/packer/azure/.pipelines/test-vhd.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm
