Repository kubernetes-sigs/image-builder, pull requests merged in 2023-03, with the labels that each got.

#1088 docs: update capi oci provider windows password docs
  docs/book/src/capi/providers/oci.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1087 Do not use same variable for managed_image_storage_account_type and SIG storage_account_type
  images/capi/packer/azure/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1091 Updating cloudbase-init version to v1.1.4
  images/capi/packer/config/windows/cloudbase-init.json
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#1039 Adding a firewall rule to enable the 22 TCP port
  images/capi/ansible/windows/roles/systemprep/tasks/ssh-archive.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1089 fix: update OCI to work on ubuntu and ensure windows tool
  images/capi/Makefile
  images/capi/packer/oci/scripts/set_bootstrap.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1093 Systemd drop-in permission fixes + disable cloud-init related drop-ins on Flatcar
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1095 Fix typos and links in Image Builder book
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/goss/goss.md
  docs/book/src/capi/providers/3dsoutscale.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/cloudstack.md
  docs/book/src/capi/providers/gcp.md
  docs/book/src/capi/providers/nutanix.md
  docs/book/src/capi/providers/oci.md
  docs/book/src/capi/providers/openstack.md
  docs/book/src/capi/providers/raw.md
  docs/book/src/capi/providers/virtualbox.md
  docs/book/src/capi/windows/windows.md
  docs/book/src/glossary.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/05_logging.cfg
  images/capi/ansible/windows/roles/load_additional_components/tasks/registry.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/url.yml
  images/capi/ansible/windows/roles/runtimes/tasks/docker_ee.yml
  images/capi/hack/image-build-ova.py
  images/capi/scripts/ci-json-sort.sh
  images/konfigadm/README.md
  images/kube-deploy/container-image/README.md
  images/kube-deploy/container-image/tools/images/container-to-raw/makedisk.sh
  v1/README.md
  v1/cmd/build.go
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1098 Update ppc64le containerd version to v1.6.19
  images/capi/packer/config/ppc64le/containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1100 Update pywinrm to v0.4.3
  images/capi/hack/ensure-ansible-windows.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1101 fix: update working with second nic for OCI image
  docs/book/src/capi/providers/oci.md
  images/capi/packer/oci/scripts/enable_second_nic.ps1
Labels: size/S, cncf-cla: yes, approved, lgtm

#1099 feat: Ubuntu 22.04 EFI Support for vSphere
  images/capi/Makefile
  images/capi/packer/ova/linux/ubuntu/http/22.04.efi/meta-data
  images/capi/packer/ova/linux/ubuntu/http/22.04.efi/user-data
  images/capi/packer/ova/ubuntu-2204-efi.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1094 Override sysctl_conf_file for Flatcar to use /etc/sysctl.d/
  images/capi/ansible/roles/node/defaults/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1110 bump containerd to 1.6.19
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1111 Update containerd wasm shims to 0.4.0
  images/capi/packer/config/wasm-shims.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1109 Re-establish prior order of the cloudbase-init plugins
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/oci/packer-windows.json
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/vbox/packer-windows.json
Labels: size/S, sig/windows, cncf-cla: yes, approved, lgtm

#1112 Add IBM Cloud related docs
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/ibmcloud.md
  docs/book/src/glossary.md
  images/capi/Makefile
Labels: size/L, cncf-cla: yes, approved, lgtm

#1105 Adding vmware datasource configuration when building ubuntu 22.04 OVA
  images/capi/ansible/roles/providers/tasks/vmware-ubuntu.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/packer/ova/ubuntu-2204-efi.json
  images/capi/packer/ova/ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1114 Bump default k8s to 1.24.11
  images/capi/packer/config/kubernetes.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1115 update capg-nigthly k8s images
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1107 Check for kube-proxy before building Azure Windows image
  images/capi/packer/azure/.pipelines/build-vhd.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1013 Add ability to build images within Openstack
  OWNERS_ALIASES
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/oci.md
  docs/book/src/capi/providers/openstack-remote.md
  images/capi/Makefile
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/openstack.yml
  images/capi/packer/openstack/OWNERS
  images/capi/packer/openstack/flatcar.json
  images/capi/packer/openstack/packer.json
  images/capi/packer/openstack/ubuntu-2004.json
  images/capi/packer/openstack/ubuntu-2204.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm
