Repository kubernetes-sigs/image-builder, pull requests merged in 2023-04, with the labels that each got.

#1126 Fix owners aliases for tide
  OWNERS_ALIASES
Labels: needs-ok-to-test, cncf-cla: yes, size/XS, lgtm

#1124 Switch to e2 machine type
  images/kube-deploy/container-image/cloudbuild.yaml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1121 Fix netword-dispatcher url for Photon builds
  images/capi/ansible/roles/providers/defaults/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1103 Modify ova/rockylinux OS type
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/rockylinux-8.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1120 Add support for RHEL 8 RAW image builds
  images/capi/Makefile
  images/capi/packer/raw/linux/rhel
  images/capi/packer/raw/raw-rhel-8.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1125 Bump containerd to 1.6.20
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1090 add /etc/cloud/cloud.cfg.d/15_azure-vnet.cfg to all Azure VMs
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/15_azure-vnet.cfg
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1128 Parameterize OS_VERSION in Azure nightly smoke test
  images/capi/packer/azure/.pipelines/smoke-test.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1092 docker: support qemu target builds
  images/capi/Dockerfile
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1135 Remove centos7 from Azure CI
  images/capi/azure_targets.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1134 Update some URL links in docs
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/oci.md
  docs/book/src/capi/providers/virtualbox.md
  docs/book/src/capi/windows/windows.md
Labels: size/M, cncf-cla: yes, approved, lgtm

#1133 Update kubeadm config file to supported API version
  images/capi/ansible/roles/kubernetes/templates/etc/kubeadm.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1136 mark the test_vhd step as failed if az capi command fails
  images/capi/packer/azure/.pipelines/test-vhd.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1117 Allow all maintainers to approve docs changes
  docs/OWNERS
Labels: size/S, cncf-cla: yes, approved, lgtm

#1145 docs: Fix WinRM link from Ansible
  docs/book/src/capi/windows/windows.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1139 Add OS_VERSION to goss for qemu
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-centos-7.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/qemu/qemu-rhel-8.json
  images/capi/packer/qemu/qemu-rockylinux-8.json
  images/capi/packer/qemu/qemu-ubuntu-1804.json
  images/capi/packer/qemu/qemu-ubuntu-2004-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2004.json
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
