Repository kubernetes-sigs/image-builder, pull requests merged in 2023-02, with the labels that each got.

#1068 Update to latest pause image from registry.k8s.io
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/roles/runtimes/defaults/main.yml
  images/capi/packer/config/common.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1003 Add support for Ubuntu 2204 for vSphere
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/packer/ova/linux/ubuntu/http/22.04/meta-data
  images/capi/packer/ova/linux/ubuntu/http/22.04/user-data
  images/capi/packer/ova/ubuntu-2204.json
  images/capi/scripts/ci-ova.sh
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1069 Goss: Remove conditional for auditd on flatcar
  images/capi/ansible/roles/node/files/etc/audit/rules.d/containerd.rules-flatcar
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/packer/goss/goss-service.yaml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1066 Feature/Azure: Support build_resource_group_name to use custom build rg
  docs/book/src/capi/providers/azure.md
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/init-sig.sh
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#997 [capi/qemu] Add ubuntu 22.04 support for qemu
  images/capi/Makefile
  images/capi/packer/ova/linux/ubuntu/http/22.04/user-data
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1074 Add note about Windows in OCI capi docs
  docs/book/src/capi/providers/oci.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1077 Fix typo in artifact_name variable
  images/capi/packer/qemu/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1081 Allow Customizing values for Azure SIG Image Definition
  images/capi/packer/azure/scripts/init-sig.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1078 Allow users to configure the QEMU VM name
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1079 Update containerd to 1.6.18, packer to 1.8.6
  images/capi/hack/ensure-packer.sh
  images/capi/packer/config/containerd.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1085 fix: Update Ubuntu 22.04 ISO for vsphere and qemu
  images/capi/packer/ova/ubuntu-2204.json
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1072 Strip arch suffix from k8s images before installing to prevent additional pull by kubeadm
  images/capi/ansible/roles/kubernetes/files/tmp/modify-k8s-img.sh
  images/capi/ansible/roles/kubernetes/tasks/url.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1084 Update refs to cluster-node-image-builder container image
  docs/book/src/capi/container-image.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1086 Add jq to CAPI Dockerfile to fix Makefile error
  images/capi/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm
