Repository kubernetes-sigs/image-builder, pull requests merged in 2023-05, with the labels that each got.

#1152 Fix Ansible failure: Invalid variable name in 'register' specified: 'import'
  images/capi/ansible/windows/roles/load_additional_components/tasks/url.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1157 Update container image docs for v0.1.15 release
  docs/book/src/capi/container-image.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1146 Remove subiquity autoinstall leftovers
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/packer/ova/linux/ubuntu/http/22.04.efi/user-data
  images/capi/packer/ova/linux/ubuntu/http/22.04/user-data
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1163 Skip Ubuntu 18.04 in ova CI tests
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1160 Add release tools and documentation
  RELEASE.md
  docs/book/src/SUMMARY.md
  docs/book/src/capi/releasing.md
  images/capi/Makefile
  images/capi/hack/ensure-kpromo.sh
  images/capi/hack/ensure-yq.sh
  images/capi/hack/get-project-maintainers.sh
Labels: size/L, kind/documentation, cncf-cla: yes, approved, lgtm

#1108 Ensure the correct Packer binary is used for image builds
  images/capi/Makefile
  images/capi/hack/ensure-packer.sh
  images/capi/hack/ensure-powervs.sh
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1166 update CAPDO owners alias
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1165 update CAPG owners alias
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1164 remove 1.23 build, add 1.27 and update others to latest release
  images/capi/packer/gce/ci/nightly/overwrite-1-23.json
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/scripts/ci-gce-nightly.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1063 Add outscale global permission image
  docs/book/src/capi/providers/3dsoutscale.md
  images/capi/packer/outscale/packer.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1159 Removing ssh user (builder) from OVA vsphere-iso
  images/capi/packer/ova/packer-node.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
