Repository kubernetes-sigs/image-builder, pull requests merged in 2023-09, with the labels that each got.

#1288 CAPI/OVA: set resource_pool for jobs and improve cleanup
  images/capi/packer/ova/packer-node.json
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1280 Install Kubernetes artifacts from pkgs.k8s.io
  images/capi/ansible/roles/kubernetes/tasks/debian.yml
  images/capi/ansible/roles/kubernetes/tasks/mariner.yml
  images/capi/ansible/roles/kubernetes/tasks/redhat.yml
  images/capi/packer/config/cni.json
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1292 Add script to ensure minimum Python version
  images/capi/Makefile
  images/capi/hack/ensure-python.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#1294 Update docs for v0.1.19 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1291 Add dracut cmd to generate initramfs with drivers for RHEL raw
  images/capi/ansible/roles/providers/tasks/raw.yml
  images/capi/packer/raw/raw-rhel-8.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1282 Add support for Proxmox
  docs/book/src/SUMMARY.md
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/proxmox.md
  images/capi/.gitignore
  images/capi/Makefile
  images/capi/packer/proxmox/config.pkr.hcl
  images/capi/packer/proxmox/linux/ubuntu/http/22.04/meta-data
  images/capi/packer/proxmox/linux/ubuntu/http/22.04/user-data
  images/capi/packer/proxmox/packer.json
  images/capi/packer/proxmox/ubuntu-2204.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1296 Update gce nightly images
  images/capi/packer/gce/ci/nightly/overwrite-1-24.json
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1299 capi: move CI to new resource pool and folder in VMC
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1300 Point how to build an image with a specific Kubernetes version in README.md
  images/capi/packer/proxmox/README.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1297 Update k8s-config logic in Azure pipeline
  images/capi/packer/azure/.pipelines/k8s-config.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1302 Bump ansible to 2.15.4
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1306 Ensure Windows and common deps are installed before ansible-lint
  images/capi/Makefile
  images/capi/ansible/python.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1305 Disable colour output with ansible-lint
  images/capi/scripts/ci-lint.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1303 Bump containerd to 1.7.6
  images/capi/packer/config/containerd.json
  images/capi/packer/config/ppc64le/containerd.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1311 [Photon]Disable tdnf cache timer
  images/capi/ansible/roles/node/tasks/photon.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1309 Update containerd_wasm_shims to v0.9.1
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
  images/capi/packer/azure/azure-config.json
  images/capi/packer/config/wasm-shims.json
  images/capi/packer/goss/goss-command.yaml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1316 Azure: added image cleanup pipeline
  images/capi/packer/azure/.pipelines/cleanup.yaml
  images/capi/packer/azure/scripts/delete-unused-storage.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1315 Fix path issues in post-processor of vsphere
  images/capi/packer/ova/packer-node.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
