Repository kubernetes-sigs/image-builder, pull requests merged in 2024-04, with the labels that each got.

#1443 photon: update photon-repos to download recent gpg keys
  images/capi/ansible/roles/setup/tasks/photon.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1439 Bump ansible-core to v2.15.10
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1438 Update Ubuntu 22.04 ISO URLs to use latest stable URLs
  images/capi/packer/ova/ubuntu-2204-efi.json
  images/capi/packer/ova/ubuntu-2204.json
  images/capi/packer/proxmox/ubuntu-2204.json
  images/capi/packer/qemu/qemu-ubuntu-2204-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1446 Update capg ci/nightly images
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
  images/capi/packer/gce/ci/nightly/overwrite-1-29.json
  images/capi/packer/gce/ci/nightly/overwrite-1-30.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1448 fix gce nightly
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
  images/capi/packer/gce/ci/nightly/overwrite-1-29.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1449 add ubuntu 22.04 for digitalocean
  images/capi/Makefile
  images/capi/packer/digitalocean/ubuntu-2204.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1451 Azure: Remove pipeline refs to CONTAINER_IMAGE
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/cleanup.yaml
  images/capi/packer/azure/.pipelines/create-disk-version.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/.pipelines/smoke-test.yaml
  images/capi/packer/azure/.pipelines/stages.yaml
  images/capi/packer/azure/.pipelines/test-vhd.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1436 Removing VirtualBox target
  docs/book/src/SUMMARY.md
  docs/book/src/capi/providers/virtualbox.md
  docs/book/src/glossary.md
  images/capi/Makefile
  images/capi/packer/vbox/OWNERS
  images/capi/packer/vbox/packer-common.json
  images/capi/packer/vbox/packer-windows.json
  images/capi/packer/vbox/vagrantfile-windows_2019.template
  images/capi/packer/vbox/windows-2019.json
  images/capi/packer/vbox/windows/enable-winrm.ps1
  images/capi/packer/vbox/windows/sysprep.ps1
  images/capi/packer/vbox/windows/windows-2019/autounattend.xml
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1450 Bump default Kubernetes to 1.28.9
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1453 add Ubuntu 24.04 LTS support for Nutanix
  docs/book/src/capi/providers/nutanix.md
  images/capi/Makefile
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/nutanix/ubuntu-2404.json
Labels: size/S, cncf-cla: yes, approved, lgtm
