Repository kubernetes-sigs/image-builder, pull requests merged in 2024-01, with the labels that each got.

#1368 Delete all rotated logs
  images/capi/ansible/roles/sysprep/tasks/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1354 Remove windows docker
  docs/book/src/capi/windows/windows.md
  images/capi/.ansible-lint-ignore
  images/capi/Makefile
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/node_windows.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/kubelet.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/wins.yml
  images/capi/ansible/windows/roles/kubernetes/templates/StartKubelet.ps1
  images/capi/ansible/windows/roles/load_additional_components/tasks/registry.yml
  images/capi/ansible/windows/roles/load_additional_components/tasks/url.yml
  images/capi/ansible/windows/roles/runtimes/tasks/docker_ee.yml
  images/capi/ansible/windows/roles/runtimes/tasks/main.yml
  images/capi/azure_targets.sh
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/ami/packer-windows.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/windows-2019-containerd-cvm.json
  images/capi/packer/azure/windows-2019-containerd.json
  images/capi/packer/azure/windows-2019.json
  images/capi/packer/azure/windows-2022-containerd-cvm.json
  images/capi/packer/azure/windows-2022-containerd.json
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/config/windows/common.json
  images/capi/packer/config/windows/docker.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-service.yaml
  images/capi/packer/nutanix/packer-windows.json
  images/capi/packer/nutanix/windows-2022.json
  images/capi/packer/oci/packer-windows.json
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/vbox/packer-windows.json
  images/capi/packer/vbox/windows-2019.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1369 Add ubuntu 22.04 for outscale
  images/capi/Makefile
  images/capi/packer/outscale/ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1370 Rockylinux image download fix
  images/capi/packer/qemu/qemu-rockylinux-8.json
  images/capi/packer/qemu/qemu-rockylinux-9.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1373 CAPI: Add option to automatically set system-reserved using formulas shared with EKS and GKE.
  docs/book/src/capi/capi.md
  images/capi/ansible/roles/kubernetes/defaults/main.yml
  images/capi/ansible/roles/kubernetes/files/usr/libexec/kubernetes/kubelet-resource-sizing.sh
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/kubernetes/templates/usr/lib/systemd/system/kubelet.service.d/11-resource-sizing.conf
  images/capi/packer/ami/packer.json
  images/capi/packer/config/ansible-args.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1375 Update docs after v0.1.22 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1377 Use openvpn from community-owned registry
  images/capi/scripts/ci-ova.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1380 Migrate interface configuration files to NetworkManager keyfiles on RHEL 9
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1382 Set root make targets to default to images/capi/Makefile
  Makefile
Labels: size/S, cncf-cla: yes, approved, lgtm

#1376 CAPI: Add kubeadm KUBECONFIG and k8s bash completion
  images/capi/ansible/roles/kubernetes/files/etc/profile.d/kubernetes.sh
  images/capi/ansible/roles/kubernetes/tasks/main.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1384 Update nightly images for gce
  images/capi/packer/gce/ci/nightly/overwrite-1-25.json
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
  images/capi/packer/gce/ci/nightly/overwrite-1-29.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1386 Bump ansible-core to v2.15.9
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm
