Repository kubernetes-sigs/image-builder, pull requests merged in 2024-08, with the labels that each got.

#1531 Update docs for image-builder v0.1.31 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: kind/documentation, size/S, cncf-cla: yes, approved, lgtm

#1534 use dirty state when releasing boskos projects
  images/capi/scripts/ci-gce.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1533 Bump default Kubernetes to 1.29.7
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1537 Fix broken Ubuntu EFI OVA builds
  images/capi/packer/ova/ubuntu-2204-efi.json
  images/capi/packer/ova/ubuntu-2404-efi.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1538 Allow specifying Flatcar version for base AMI
  images/capi/packer/ami/flatcar.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1539 Updated docs for v0.1.32
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1540 Better handling of Flatcar iso boot command
  images/capi/packer/ova/flatcar.json
  images/capi/packer/qemu/qemu-flatcar.json
  images/capi/packer/raw/raw-flatcar.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1542 Updated docs for v0.1.33
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1543 Update containerd
  images/capi/packer/config/containerd.json
  images/capi/packer/config/ppc64le/containerd.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1546 Patch feature flags directly into cloud-init code since newer versions do not load `feature_overrides.py` anymore
  images/capi/ansible/roles/providers/files/cloud-init-features.patch
  images/capi/ansible/roles/providers/tasks/main.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1545 Set correct Guest OS type to Windows Server 2022 for VMware OVAs
  images/capi/packer/ova/windows-2022-efi.json
  images/capi/packer/ova/windows-2022.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1548 Update guest types for VMware Windows 2019 and 2022 OVA
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/windows-2019-efi.json
  images/capi/packer/ova/windows-2019.json
  images/capi/packer/ova/windows-2022-efi.json
  images/capi/packer/ova/windows-2022.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1550 fix: unrooted path for 90proxy file
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1551 Fix timesyncd support in latest Flatcar release for Azure
  images/capi/ansible/roles/providers/tasks/azure.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1552 Pin base container image to Ubuntu 24.04
  images/capi/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1547 Install AWS CLI with --update flag
  images/capi/ansible/roles/providers/tasks/awscliv2.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1553 Updated docs for release v0.1.34
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1556 Ensure systemd-timesyncd service is started on Flatcar
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/ansible/roles/setup/tasks/flatcar.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1557 Disable Goss inspect_mode to have validation failures fail the image …
  images/capi/packer/config/goss-args.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
