Repository kubernetes-sigs/image-builder, pull requests merged in 2024-09, with the labels that each got.

#1561 Update Ubuntu 24.04 to latest (pinned) ISO
  images/capi/packer/ova/ubuntu-2404-efi.json
  images/capi/packer/ova/ubuntu-2404.json
  images/capi/packer/proxmox/ubuntu-2404.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1511 Azure: Allow the configuration of cloud_environment_name
  images/capi/packer/azure/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1563 start and enable `networkd-dispatcher` during proxmox build
  images/capi/ansible/roles/providers/tasks/proxmox.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1558 add proxmox rockylinux 9
  images/capi/Makefile
  images/capi/packer/proxmox/linux/rockylinux/http/9/ks.cfg
  images/capi/packer/proxmox/packer.json
  images/capi/packer/proxmox/rockylinux-9.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1567 Update Ubuntu 22.04 to latest point release and checksum
  images/capi/packer/ova/ubuntu-2204-efi.json
  images/capi/packer/ova/ubuntu-2204.json
  images/capi/packer/proxmox/ubuntu-2204.json
  images/capi/packer/qemu/qemu-ubuntu-2204-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1564 add disk size and type to gcs/packer.json
  images/capi/packer/gce/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1566 Add vnc_bind_address var to QEMU builder
  images/capi/packer/qemu/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1568 Update docs for release v0.1.35
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1569 Fix Goss variables for RHEL-based images
  images/capi/packer/goss/goss-vars.yaml
Labels: size/L, cncf-cla: yes, approved, lgtm

#1570 Add optional support for including ecr-credential-provider
  docs/book/src/SUMMARY.md
  docs/book/src/capi/ecr-credential-provider.md
  images/capi/.ansible-lint-ignore
  images/capi/Makefile
  images/capi/ansible/node.yml
  images/capi/ansible/roles/ecr_credential_provider/defaults/main.yml
  images/capi/ansible/roles/ecr_credential_provider/tasks/main.yaml
  images/capi/ansible/roles/ecr_credential_provider/templates/var/usr/ecr-credential-provider/ecr-credential-provider-config
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/ecr_credential_provider.json
  images/capi/packer/config/windows/ansible-args-windows.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1571 Updated docs for release v0.1.36
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1572 cleanup: Use artifacts.k8s.io instead of storage.googleapis.com for ECR credential provider
  .gitignore
  images/capi/ansible/roles/ecr_credential_provider/defaults/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1573 fix(qemu-ubuntu-2404): update URL to 24.04.1 image
  images/capi/packer/qemu/qemu-ubuntu-2404.json
Labels: needs-ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
