Repository kubernetes-sigs/image-builder, pull requests merged in 2024-06, with the labels that each got.

#1480 Remove 90-installer-network.cfg on ubuntu, left by recent subiquity
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1486 cloud-init: improve logging to stream logs to the cloud-init-output.log file instead of dumping at the end
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/05_logging.cfg
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1483 Match ubuntu grub configuration with Canonical cloud-images
  images/capi/ansible/roles/sysprep/files/etc/default/grub.d/50-cloudimg-settings.cfg
  images/capi/ansible/roles/sysprep/handlers/main.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1383 pin packer version to 1.9.5
  images/capi/hack/ensure-packer.sh
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm, kind/cleanup

#1488 Updating photon gpg keys should not enable disabled repo
  images/capi/ansible/roles/setup/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1469 Make sure nouveau kernel module is never loaded
  images/capi/ansible/roles/gpu/defaults/main.yml
  images/capi/ansible/roles/gpu/tasks/main.yml
  images/capi/ansible/roles/gpu/templates/etc/modprobe.d/blocklist-nouveau.conf
  images/capi/packer/config/ansible-args.json
  images/capi/packer/goss/goss-files.yaml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/packer-node.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1490 Update docs for v0.1.30
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1461 Add Ubuntu 24.04 for GCE
  docs/book/src/capi/providers/gcp.md
  images/capi/Makefile
  images/capi/packer/gce/ubuntu-2404.json
Labels: kind/feature, size/S, cncf-cla: yes, approved, lgtm

#1492 🌱 move to cx22 types for hcloud
  images/capi/packer/hcloud/hcloud-config.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1494 Optionally source /etc/default/kubelet in kubelet.service
  images/capi/ansible/roles/kubernetes/templates/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1493 Only modify grub configuration if update-grub command is present
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1499 Add vultr packer provider
  docs/book/src/capi/providers/vultr.md
  images/capi/Makefile
  images/capi/packer/vultr/config.pkr.hcl
  images/capi/packer/vultr/packer.json
  images/capi/packer/vultr/ubuntu-2204.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm
