Repository kubernetes-sigs/image-builder, pull requests merged in 2024-05, with the labels that each got.

#1452 Adding optional security tools
  images/capi/ansible/roles/security/README.md
  images/capi/ansible/roles/security/defaults/main.yml
  images/capi/ansible/roles/security/tasks/falco.yml
  images/capi/ansible/roles/security/tasks/main.yml
  images/capi/ansible/roles/security/tasks/trivy.yml
Labels: kind/feature, size/L, cncf-cla: yes, approved, lgtm

#1456 Add Ubuntu 24.04 LTS for DigitalOcean
  docs/book/src/capi/providers/digitalocean.md
  images/capi/Makefile
  images/capi/packer/digitalocean/ubuntu-2404.json
Labels: kind/feature, size/S, cncf-cla: yes, approved, lgtm

#1457 Add Ubuntu 24.04 LTS for AWS
  docs/book/src/capi/providers/aws.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/ansible/roles/providers/tasks/awscliv2.yml
  images/capi/packer/ami/ubuntu-2404.json
  images/capi/packer/goss/goss-vars.yaml
Labels: kind/feature, size/L, cncf-cla: yes, approved, lgtm

#1455 Add instruction to build DHCP configured images
  docs/book/src/capi/providers/ibmcloud.md
  images/capi/hack/ensure-powervs.sh
  images/capi/packer/powervs/packer.json
Labels: kind/documentation, size/M, cncf-cla: yes, approved, lgtm

#1458 Don't install Azure CLI by default
  docs/book/src/capi/providers/azure.md
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/ansible/roles/providers/tasks/azurecli.yml
  images/capi/ansible/roles/providers/tasks/debian.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/mariner.yml
  images/capi/ansible/roles/providers/tasks/redhat.yml
  images/capi/ansible/windows/roles/providers/tasks/azure.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/L, cncf-cla: yes, approved, lgtm, kind/cleanup

#1454 Add Ubuntu 24.04 LTS for Azure
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/ubuntu-2404-cvm.json
  images/capi/packer/azure/ubuntu-2404-gen2.json
  images/capi/packer/azure/ubuntu-2404.json
Labels: kind/feature, size/M, cncf-cla: yes, approved, lgtm

#1463 allow override of ubuntu repository urls with ubuntu_repo,ubuntu_security_repo variables
  images/capi/ansible/roles/setup/templates/etc/apt/sources.list.j2
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1464 Update Rocky Linux 9 ISO URLs
  images/capi/ansible/roles/providers/tasks/vmware-redhat.yml
  images/capi/packer/ova/rockylinux-9.json
  images/capi/packer/qemu/qemu-rockylinux-9.json
Labels: ok-to-test, tide/merge-method-squash, size/M, cncf-cla: yes, approved, lgtm

#1465 Add Azure Linux 3 for Azure
  docs/book/src/capi/goss/goss.md
  images/capi/.ansible-lint-ignore
  images/capi/Makefile
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/limit-nofile.conf
  images/capi/ansible/roles/kubernetes/tasks/azurelinux.yml
  images/capi/ansible/roles/kubernetes/tasks/main.yml
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/azurecli.yml
  images/capi/ansible/roles/setup/tasks/azurelinux.yml
  images/capi/ansible/roles/setup/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/azurelinux.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/azure_targets.sh
  images/capi/packer/azure/azurelinux-3-gen2.json
  images/capi/packer/azure/azurelinux-3.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/new-sku.sh
  images/capi/packer/goss/goss-vars.yaml
Labels: kind/feature, size/L, area/provider/azure, cncf-cla: yes, approved, lgtm

#1440 update the way to install cloud-init
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/99_metadata.cfg
  images/capi/ansible/roles/providers/tasks/outscale.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm, kind/cleanup

#1471 Updated docs for v0.1.26
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1467 Fix PowerVS builds by including wasm-shims file
  images/capi/Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1473 Update docs for v0.1.27
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
  images/capi/scripts/release-update-docs.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1475 In packer/openstack, add "source_image_filter" to select source image by name
  images/capi/packer/openstack/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1476 RHEL9 OVA
  images/capi/Makefile
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/linux/rhel/http/9/ks.cfg
  images/capi/packer/ova/rhel-9.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1478 Update docs for v0.1.28
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1479 Update docs for v0.1.29
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm
