Repository kubernetes-sigs/image-builder, pull requests merged in 2024-03, with the labels that each got.

#1420 Update ISO URLs to latest, add script to update ISO checksums
  images/capi/Makefile
  images/capi/hack/update-iso-checksums.sh
  images/capi/packer/ova/rockylinux-8.json
  images/capi/packer/ova/ubuntu-2204-efi.json
  images/capi/packer/ova/ubuntu-2204.json
  images/capi/packer/proxmox/packer.json
  images/capi/packer/proxmox/ubuntu-2204.json
  images/capi/packer/qemu/qemu-centos-9.json
  images/capi/packer/qemu/qemu-ubuntu-2004-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2004.json
  images/capi/packer/qemu/qemu-ubuntu-2204-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2204.json
  images/capi/packer/qemu/qemu-ubuntu-2304.json
  images/capi/packer/raw/raw-ubuntu-2004-efi.json
  images/capi/packer/raw/raw-ubuntu-2004.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1426 docs: Updated docs for 0.1.25 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1425 Add QEMU support for RHEL 9
  images/capi/Makefile
  images/capi/packer/qemu/qemu-rhel-9.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1424 fix(outscale): Configure ec2 provider so VM userdata will work again
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/99_metadata.cfg
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1427 Add raw image building support for rhel-9 and rhel-9 efi
  images/capi/Makefile
  images/capi/packer/raw/linux/rhel
  images/capi/packer/raw/linux/rhel/7/ks.cfg
  images/capi/packer/raw/linux/rhel/8/ks.cfg
  images/capi/packer/raw/linux/rhel/9/ks-efi.cfg
  images/capi/packer/raw/linux/rhel/9/ks.cfg
  images/capi/packer/raw/packer.json
  images/capi/packer/raw/raw-rhel-9-efi.json
  images/capi/packer/raw/raw-rhel-9.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1432 Place RHEL kickstart files for raw builds in `http` directory
  images/capi/packer/raw/linux/rhel/http/7/ks.cfg
  images/capi/packer/raw/linux/rhel/http/8/ks.cfg
  images/capi/packer/raw/linux/rhel/http/9/ks-efi.cfg
  images/capi/packer/raw/linux/rhel/http/9/ks.cfg
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1431 Revert updates to Ubuntu 2004 ISO URLs
  images/capi/packer/qemu/qemu-ubuntu-2004-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2004.json
  images/capi/packer/raw/raw-ubuntu-2004-efi.json
  images/capi/packer/raw/raw-ubuntu-2004.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1433 Replace symlink OS folders with actual folders, remove unused kickstart/preseed configs
  images/capi/packer/ova/linux/photon/http/4
  images/capi/packer/ova/linux/photon/http/4/ks.json
  images/capi/packer/ova/linux/rhel
  images/capi/packer/ova/linux/rhel/http/7/ks.cfg
  images/capi/packer/ova/linux/rhel/http/8/ks.cfg
  images/capi/packer/ova/linux/ubuntu/http/18.04/preseed.cfg
  images/capi/packer/qemu/linux/photon/http/4
  images/capi/packer/qemu/linux/rhel
  images/capi/packer/qemu/linux/rhel/http/8/ks.cfg
  images/capi/packer/qemu/linux/rhel/http/9/ks.cfg
  images/capi/packer/qemu/linux/ubuntu/http/18.04/preseed.cfg
  images/capi/packer/raw/linux/ubuntu/http/18.04/preseed.cfg
Labels: size/L, cncf-cla: yes, approved, lgtm

#1435 Add NetworkConfigPlugin to VMware cloudbase-init plugin list
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/ova/packer-windows.json
Labels: cncf-cla: yes, size/XS, approved, lgtm
