Repository kubernetes-sigs/image-builder, pull requests merged in 2024-12, with the labels that each got.

#1578 Add pipeline for Azure community gallery image publishing
  images/capi/packer/azure/.pipelines/build-sig.yaml
  images/capi/packer/azure/.pipelines/build-vhd.yaml
  images/capi/packer/azure/.pipelines/clean-sig.yaml
  images/capi/packer/azure/.pipelines/cleanup.yaml
  images/capi/packer/azure/.pipelines/create-disk-version.yaml
  images/capi/packer/azure/.pipelines/create-sku.yaml
  images/capi/packer/azure/.pipelines/delete-storage-account.yaml
  images/capi/packer/azure/.pipelines/generate-sas.yaml
  images/capi/packer/azure/.pipelines/promote-sig.yaml
  images/capi/packer/azure/.pipelines/sig-publishing-info.yaml
  images/capi/packer/azure/.pipelines/smoke-test.yaml
  images/capi/packer/azure/.pipelines/stages.yaml
  images/capi/packer/azure/.pipelines/test-sig.yaml
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/.pipelines/vhd-publishing-info.yaml
  images/capi/packer/azure/config.pkr.hcl
  images/capi/packer/azure/packer.json
  images/capi/packer/azure/scripts/delete-unused-storage.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/new-disk-version.sh
  images/capi/packer/azure/scripts/new-sku.sh
Labels: size/XXL, cncf-cla: yes, approved, lgtm

#1632 fix(amazon-2): epel, install kubernetes steps
  images/capi/ansible/roles/kubernetes/tasks/redhat.yml
  images/capi/ansible/roles/setup/tasks/redhat.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1644 Updated docs for release v0.1.40
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1646 Fix state for Ansible RHSM repository module
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1645 fix(ansible/openstack): run networkd-dispatcher only on debian
  images/capi/ansible/roles/providers/tasks/openstack.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1649 Update rocky linux image url
  images/capi/packer/ova/rockylinux-9.json
  images/capi/packer/proxmox/rockylinux-9.json
  images/capi/packer/qemu/qemu-rockylinux-9.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1648 Enable cleanup for /var/log/messages on Photon for vSphere Provider
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/providers/defaults/main.yml
  images/capi/ansible/roles/providers/tasks/vmware-photon.yml
  images/capi/ansible/roles/providers/templates/etc/logrotate.d/messages.j2
  images/capi/packer/goss/goss-vars.yaml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1652 ci(docker): add OCI labels to the Docker image
  images/capi/Dockerfile
  images/capi/Makefile
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1653 Bump ansible-core to v2.15.3
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1640 feat(ami): Support Amazon Linux 2023
  images/capi/Makefile
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/ansible/roles/node/meta/main.yml
  images/capi/ansible/roles/node/tasks/amazonLinux.yml
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
  images/capi/packer/ami/amazon-2.json
  images/capi/packer/ami/amazon-2023.json
  images/capi/packer/goss/goss-vars.yaml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1589 Add flatcar build for Proxmox
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/proxmox.yml
  images/capi/packer/proxmox/README.md
  images/capi/packer/proxmox/flatcar.json
  images/capi/packer/proxmox/packer.json.tmpl
Labels: size/M, cncf-cla: yes, approved, lgtm
