Repository kubernetes-sigs/image-builder, pull requests merged in 2024-02, with the labels that each got.

#1388 Add timeout to Goss test for Windows AZ CLI
  images/capi/packer/goss/goss-command.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1385 Use specific CNI package only if defined
  images/capi/ansible/roles/kubernetes/tasks/debian.yml
  images/capi/ansible/roles/kubernetes/tasks/mariner.yml
  images/capi/ansible/roles/kubernetes/tasks/photon.yml
  images/capi/ansible/roles/kubernetes/tasks/redhat.yml
  images/capi/hack/generate-goss-specs.py
  images/capi/packer/config/cni.json
  images/capi/packer/goss/goss-package.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1389 patch: qemu efi fixes
  images/capi/packer/qemu/linux/ubuntu/http/22.04.efi.qemu/user-data
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1393 Bump containerd to 1.7.13
  images/capi/packer/config/containerd.json
  images/capi/packer/config/ppc64le/containerd.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1398 Flatcar build fix
  images/capi/packer/azure/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1391 Update CAPZ test templates used in pipeline
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/scripts/test-templates/linux/kustomization.yaml
  images/capi/packer/azure/scripts/test-templates/windows/kustomization.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1401 Update the GitHub issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#1403 patch: fix boolean condition for kubernetes_enable_automatic_resource_sizing
  images/capi/ansible/roles/kubernetes/tasks/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1402 patch: new GPU role to support both AMD and NVIDIA drivers
  .gitignore
  images/capi/.ansible-lint-ignore
  images/capi/ansible/roles/gpu/README.md
  images/capi/ansible/roles/gpu/defaults/main.yml
  images/capi/ansible/roles/gpu/tasks/amd.yml
  images/capi/ansible/roles/gpu/tasks/main.yml
  images/capi/ansible/roles/gpu/tasks/nvidia.yml
  images/capi/ansible/roles/gpu/templates/gridd.conf.j2
  images/capi/ansible/roles/nvidia/README.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#1392 Support Azure OOT credential provider
  images/capi/ansible/roles/providers/tasks/azure.yml
  images/capi/ansible/windows/roles/providers/tasks/azure.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1407 Remove unneeded pip and package upgrade
  images/capi/ansible/roles/providers/tasks/debian.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1405 Update wasm-shims to v0.11.1
  images/capi/packer/config/wasm-shims.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1409 fix(outscale): Remove cloud-init obsolete installation package
  images/capi/ansible/roles/providers/files/tmp/cloud-init_22.2-outscale.deb
  images/capi/ansible/roles/providers/tasks/outscale.yml
  images/capi/packer/outscale/ubuntu-2204.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1411 Update docs for 0.1.24 & include new script to handle the docs updates
  Makefile
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
  images/capi/scripts/release-update-docs.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1400 Set HOME_MODE to 0700 in Flatcar images
  images/capi/ansible/roles/node/tasks/main.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1371 Set the pipefail option
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/photon.yml
  images/capi/ansible/roles/sysprep/tasks/redhat.yml
Labels: size/S, ok-to-test, tide/merge-method-squash, cncf-cla: yes, approved, lgtm

#1412 Update qemu ubuntu 22.04
  images/capi/packer/qemu/qemu-ubuntu-2204-efi.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1415 fix: Increase waiting for GRUB
  images/capi/packer/qemu/qemu-ubuntu-2204.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1413 Promote drew-viles to maintainer
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1419 update nightly build images for capg
  images/capi/packer/gce/ci/nightly/overwrite-1-26.json
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
  images/capi/packer/gce/ci/nightly/overwrite-1-29.json
Labels: size/S, cncf-cla: yes, approved, lgtm
