Repository kubernetes-sigs/image-builder, pull requests merged in 2024-07, with the labels that each got.

#1501 Add containerd configuration for hosts.toml paths
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/ansible/roles/containerd/templates/etc/containerd/config.toml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1500 Add centos-9 support for CAPIBM PowerVS images
  docs/book/src/capi/providers/ibmcloud.md
  images/capi/Makefile
  images/capi/packer/powervs/centos-9.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1485 Add cloud image based qemu builds
  images/capi/Makefile
  images/capi/ansible/firstboot.yml
  images/capi/packer/qemu/cloud-init/meta-data
  images/capi/packer/qemu/cloud-init/user-data
  images/capi/packer/qemu/packer.json
  images/capi/packer/qemu/qemu-rockylinux-8-cloudimg.json
  images/capi/packer/qemu/qemu-rockylinux-9-cloudimg.json
  images/capi/packer/qemu/qemu-ubuntu-2204-cloudimg.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1491 Add Ubuntu 24.02 for QEMU
  images/capi/Makefile
  images/capi/packer/qemu/linux/ubuntu/http/24.04/meta-data
  images/capi/packer/qemu/linux/ubuntu/http/24.04/user-data
  images/capi/packer/qemu/qemu-ubuntu-2404.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1506 Proxmox network requirements
  docs/book/src/capi/providers/proxmox.md
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1507 Allow Azure auth with federated token in scripts
  images/capi/packer/azure/.pipelines/delete-storage-account.yaml
  images/capi/packer/azure/.pipelines/generate-sas.yaml
  images/capi/packer/azure/.pipelines/test-vhd.yaml
  images/capi/packer/azure/scripts/delete-unused-storage.sh
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/M, area/provider/azure, cncf-cla: yes, approved, lgtm, kind/cleanup

#1509 Use AZURE_STORAGE_AUTH_MODE with federated auth
  images/capi/packer/azure/.pipelines/generate-sas.yaml
  images/capi/packer/azure/scripts/delete-unused-storage.sh
  images/capi/packer/azure/scripts/init-vhd.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1514 Enable use_azure_cli_auth in Packer plugin
  images/capi/packer/azure/azure-config.json
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/packer.json
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1521 Update Azure e2e test regions and log in each SIG build
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/scripts/init-vhd.sh
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1519 Use UTC+0 for system clock in Windows VMware OVA
  images/capi/packer/ova/windows/windows-2019-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2019/autounattend.xml
  images/capi/packer/ova/windows/windows-2022-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2022/autounattend.xml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1498 fix(packer/openstack): allow availability_zone
  images/capi/packer/openstack/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1522 adding a make target for openstack-ubuntu-2404
  images/capi/Makefile
  images/capi/packer/openstack/ubuntu-2404.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1526 Load packer goss plugin via config file
  images/capi/Makefile
  images/capi/hack/ensure-goss.sh
  images/capi/packer/config.pkr.hcl
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1529 Set the system real clock to UTC in cloudbase-init
  images/capi/ansible/windows/example.vars.yml
  images/capi/ansible/windows/roles/cloudbase-init/templates/cloudbase-init.conf
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/config/windows/cloudbase-init.json
  images/capi/packer/ova/packer-windows.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1530 Add ubuntu 24.04 for Proxmox
  docs/book/src/capi/providers/proxmox.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/providers/tasks/proxmox.yml
  images/capi/packer/proxmox/linux/ubuntu/http/24.04/meta-data
  images/capi/packer/proxmox/linux/ubuntu/http/24.04/user-data
  images/capi/packer/proxmox/packer.json
  images/capi/packer/proxmox/ubuntu-2404.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm
