Repository kubernetes-sigs/image-builder, pull requests merged in 2024-10, with the labels that each got.

#1574 outscale: user can define vm_type
  images/capi/packer/outscale/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1527 Add WS2025 SIG
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/packer-windows.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/windows-2025-containerd.json
  images/capi/packer/config/goss-args.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-package.yaml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1575 Feature: add support for qemu-ubuntu-2404-efi
  images/capi/Makefile
  images/capi/packer/qemu/linux/ubuntu/http/24.04.efi/meta-data
  images/capi/packer/qemu/linux/ubuntu/http/24.04.efi/user-data
  images/capi/packer/qemu/qemu-ubuntu-2404-efi.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1577 Bump default Kubernetes to 1.30.5
  images/capi/packer/config/kubernetes.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1587 [Proxmox] Add possibilty to set iso_file or iso_url and add Disk Format to qcow2
  images/capi/packer/proxmox/README.md
  images/capi/packer/proxmox/packer.json
  images/capi/packer/proxmox/ubuntu-2204.json
  images/capi/packer/proxmox/ubuntu-2404.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1586 fix(capi-ubuntu24): pin cloud-init deb package version
  images/capi/packer/ami/ubuntu-2404.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1590 fix: pin cloud-init for ubuntu 22.04 image
  images/capi/packer/ami/ubuntu-2204.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1582 fix: update packer qemu plugin name
  images/capi/packer/oci/config.pkr.hcl
  images/capi/packer/outscale/config.pkr.hcl
  images/capi/packer/qemu/config.pkr.hcl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1592 Update docs for v0.1.37
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1595 Ensure builder user is cleaned up for Proxmox provider
  images/capi/packer/proxmox/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1596 Set random ssh password for builder
  images/capi/packer/nutanix/packer.json
  images/capi/packer/ova/packer-common.json
  images/capi/packer/proxmox/packer.json
  images/capi/packer/qemu/packer.json
  images/capi/packer/raw/packer.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1597 Update docs for v0.1.38
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1608 docs(gcp): add configuration examples
  docs/book/src/capi/providers/gcp.md
Labels: size/S, needs-ok-to-test, cncf-cla: yes, approved, lgtm

#1604 Remove windows-2019 and -2025 targets from CI
  images/capi/azure_targets.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1600 Install gcloud from rpm on gce rhel8
  images/capi/ansible/roles/providers/tasks/googlecompute.yml
Labels: size/M, cncf-cla: yes, approved, lgtm

#1581 Use external googlecompute packer plugin
  images/capi/Makefile
  images/capi/packer/gce/config.pkr.hcl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1609 outscale: fix goss error: <.Vars.OS_VERSION>: map has no entry for key "OS_VERSION"
  images/capi/packer/outscale/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1599 Update Azure Linux 3 base image source
  images/capi/ansible/roles/setup/tasks/azurelinux.yml
  images/capi/azure_targets.sh
  images/capi/packer/azure/azurelinux-3-gen2.json
  images/capi/packer/azure/azurelinux-3.json
Labels: size/S, cncf-cla: yes, approved, lgtm, kind/regression

#1613 Update docs for v0.1.39
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1614 Fix user-data filename in Nutanix gitignore
  images/capi/packer/nutanix/.gitignore
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1621 Bump ansible-core to v2.15.2
  images/capi/hack/ensure-ansible.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm, kind/cleanup

#1615 Pin Azure windows-2019 to known working version
  images/capi/packer/azure/windows-2019-containerd.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1619 Skip Get-WindowsFeature goss spec for windows-2025
  images/capi/azure_targets.sh
  images/capi/packer/goss/goss-package.yaml
Labels: sig/windows, cncf-cla: yes, size/XS, approved, lgtm

#1616 outscale: user can make OMI publicly accessible or not
  images/capi/packer/outscale/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1623 update packe google compute plugin
  images/capi/packer/gce/config.pkr.hcl
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1624 add rhel image info and cleanup
  images/capi/scripts/ci-gce.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1612 add example proxmox build using image-builder container
  docs/book/src/capi/container-image.md
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1576 Fix gMSA setup on Windows
  docs/book/src/capi/windows/windows.md
  images/capi/ansible/windows/roles/gmsa/files/install-gmsa-keyvault-plugin.ps1
  images/capi/ansible/windows/roles/gmsa/tasks/gmsa_keyvault.yml
  images/capi/packer/goss/goss-command.yaml
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm
