Repository kubernetes-sigs/image-builder, pull requests merged in 2025-03, with the labels that each got.

#1699 Add 3 regions for replication to Azure pipeline
  images/capi/packer/azure/.pipelines/promote-sig.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1700 drop 1.28/29 add 1.31/32 and update others to latest release
  images/capi/packer/gce/ci/nightly/overwrite-1-27.json
  images/capi/packer/gce/ci/nightly/overwrite-1-28.json
  images/capi/packer/gce/ci/nightly/overwrite-1-29.json
  images/capi/packer/gce/ci/nightly/overwrite-1-30.json
  images/capi/packer/gce/ci/nightly/overwrite-1-31.json
  images/capi/packer/gce/ci/nightly/overwrite-1-32.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1704 Remove Duplicate (and broken) oem_id in Proxmox
  images/capi/packer/proxmox/packer.json.tmpl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1703 Broken Ubuntu Download Link + Bad merge on proxmox/packer.json.tmpl
  images/capi/packer/ova/ubuntu-2404-efi.json
  images/capi/packer/ova/ubuntu-2404.json
  images/capi/packer/proxmox/README.md
  images/capi/packer/proxmox/ubuntu-2404-efi.json
  images/capi/packer/proxmox/ubuntu-2404.json
  images/capi/packer/qemu/qemu-ubuntu-2404-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2404.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1698 kubeReserved bugfix for instances >130GiB memory
  images/capi/ansible/roles/kubernetes/files/usr/libexec/kubernetes/kubelet-resource-sizing.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
