Repository kubernetes-sigs/image-builder, pull requests merged in 2025-01, with the labels that each got.

#1660 Make image-build-flatcar.sh POSIX-compliant
  images/capi/hack/image-build-flatcar.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1663 fix: goss-command.yml gathers kube image names
  images/capi/packer/goss/goss-command.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1661 Bump default Kubernetes to 1.31.4
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1674 Compatibility fixes for ssh password script
  images/capi/hack/set-ssh-password.sh
Labels: size/S, cncf-cla: yes, approved, lgtm, kind/cleanup

#1671 Add Ubuntu 2204 target to the RAW builder.
  images/capi/Makefile
  images/capi/packer/raw/.gitignore
  images/capi/packer/raw/linux/ubuntu/http/22.04.efi/meta-data
  images/capi/packer/raw/linux/ubuntu/http/22.04.efi/user-data.tmpl
  images/capi/packer/raw/linux/ubuntu/http/22.04/meta-data
  images/capi/packer/raw/linux/ubuntu/http/22.04/user-data.tmpl
  images/capi/packer/raw/packer.json.tmpl
  images/capi/packer/raw/raw-ubuntu-2004-efi.json
  images/capi/packer/raw/raw-ubuntu-2004.json
  images/capi/packer/raw/raw-ubuntu-2204-efi.json
  images/capi/packer/raw/raw-ubuntu-2204.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1668 Fixes the Windows update categories are not correctly set
  images/capi/ansible/windows/roles/systemprep/defaults/main.yml
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1583 chore: changes for building CAPA amis
  images/capi/ansible/roles/providers/files/etc/cloud/cloud.cfg.d/90_dpkg.cfg
  images/capi/ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py
  images/capi/ansible/roles/providers/tasks/aws.yml
  images/capi/packer/ami/ubuntu-2204.json
  images/capi/packer/ami/ubuntu-2404.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1677 feat(ansible): add management for multipath.conf file
  images/capi/ansible/roles/multipathd/README.md
  images/capi/ansible/roles/multipathd/defaults/main.yml
  images/capi/ansible/roles/multipathd/files/multipath.conf
  images/capi/ansible/roles/multipathd/tasks/main.yml
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm
