Repository kubernetes-sigs/image-builder, pull requests merged in 2025-05, with the labels that each got.

#1675 fix: added nvidia_ceph default values to the gpu role
  images/capi/ansible/roles/gpu/README.md
  images/capi/ansible/roles/gpu/defaults/main.yml
  images/capi/ansible/roles/gpu/tasks/nvidia.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1729 fix: automatic resource sizing script & add kubelet sysconfig path for DEB systems
  images/capi/ansible/roles/kubernetes/files/usr/libexec/kubernetes/kubelet-resource-sizing.sh
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1731 docs: Fix ami variable descriptions and add missing default value
  docs/book/src/capi/providers/aws.md
Labels: size/S, needs-ok-to-test, cncf-cla: yes, approved, lgtm

#1734 Update docker/dockerfile to version 1.14
  images/capi/Dockerfile
  images/capi/Makefile
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1735 Update govc to v0.49.0
  images/capi/scripts/ci-ova.sh
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1739 refactor no swap for ova/ubuntu
  images/capi/packer/ova/linux/ubuntu/http/22.04.efi/user-data.tmpl
  images/capi/packer/ova/linux/ubuntu/http/22.04/user-data.tmpl
  images/capi/packer/ova/linux/ubuntu/http/24.04.efi/user-data.tmpl
  images/capi/packer/ova/linux/ubuntu/http/24.04/user-data.tmpl
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1742 fix(ansible/sysprep/tasks/debian) : step name typo
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1725 feat(packer/outscale): define omi_name as user
  images/capi/packer/outscale/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1744 Populate the AMIs 'Name' tag with the build name
  images/capi/packer/ami/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1723 feat(raw): add ubuntu 24.04 target
  images/capi/Makefile
  images/capi/packer/raw/linux/ubuntu/http/24.04.efi/meta-data
  images/capi/packer/raw/linux/ubuntu/http/24.04.efi/user-data.tmpl
  images/capi/packer/raw/linux/ubuntu/http/24.04/meta-data
  images/capi/packer/raw/linux/ubuntu/http/24.04/user-data.tmpl
  images/capi/packer/raw/raw-ubuntu-2404-efi.json
  images/capi/packer/raw/raw-ubuntu-2404.json
Labels: size/L, ok-to-test, cncf-cla: yes, approved, lgtm

#1737 Better sed expression
  images/capi/ansible/roles/providers/files/usr/local/bin/modify-cloud-init-cfg.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1748 Bump default Kubernetes to 1.32.4
  images/capi/packer/config/kubernetes.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1745 install packer-plugin-vsphere
  images/capi/Makefile
  images/capi/packer/ova/config.pkr.hcl
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1746 Ansible: stop rsyslog only if installed
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1749 Update docs for v0.1.43
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1755 Allow overriding buildkit syntax
  images/capi/Dockerfile
  images/capi/Makefile
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1758 Use correct user value for AMI Name tag
  images/capi/packer/ami/packer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1759 Bump packer-plugin-powervs to 0.2.10
  images/capi/hack/ensure-powervs.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm
