Repository kubernetes-sigs/image-builder, pull requests merged in 2025-04, with the labels that each got.

#1710 Update Packer VM hardware version for RHEL 9 OVA builds
  images/capi/hack/image-build-ova.py
  images/capi/packer/ova/rhel-9.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1711 Update VMware tools to latest 12.5.1 for VMware OVA configuration
  images/capi/packer/ova/windows-2019-efi.json
  images/capi/packer/ova/windows-2019.json
  images/capi/packer/ova/windows-2022-efi.json
  images/capi/packer/ova/windows-2022.json
  images/capi/packer/ova/windows/windows-2019-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2019/autounattend.xml
  images/capi/packer/ova/windows/windows-2022-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2022/autounattend.xml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1717 fix: Duplicate kubelet parameter by automatic resource sizing script
  images/capi/ansible/roles/kubernetes/files/usr/libexec/kubernetes/kubelet-resource-sizing.sh
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1720 Add LimitNOFILE configuration for Flatcar OS
  images/capi/ansible/roles/containerd/tasks/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1706 Adding RockyLinux to openstack
  images/capi/Makefile
  images/capi/ansible/roles/security/tasks/falco.yml
  images/capi/ansible/roles/security/tasks/trivy.yml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/openstack/packer.json
  images/capi/packer/openstack/rockylinux-9.json
Labels: size/L, cncf-cla: yes, approved, lgtm
