Repository kubernetes-sigs/image-builder, pull requests merged in 2025-08, with the labels that each got.

#1816 Allow users to pass custom Packer GitHub API token value
  docs/book/src/capi/container-image.md
  images/capi/Dockerfile
  images/capi/Makefile
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1793 Remove Ubuntu 20.04 as end of life
  docs/book/src/capi/container-image.md
  docs/book/src/capi/providers/3dsoutscale.md
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/azure.md
  docs/book/src/capi/providers/cloudstack.md
  docs/book/src/capi/providers/digitalocean.md
  docs/book/src/capi/providers/hcloud.md
  docs/book/src/capi/providers/ibmcloud.md
  docs/book/src/capi/providers/nutanix.md
  docs/book/src/capi/providers/oci.md
  docs/book/src/capi/providers/openstack-remote.md
  docs/book/src/capi/providers/openstack.md
  docs/book/src/capi/providers/raw.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/ami/ubuntu-2004.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/azure/ubuntu-2004-cvm.json
  images/capi/packer/azure/ubuntu-2004-gen2.json
  images/capi/packer/azure/ubuntu-2004.json
  images/capi/packer/digitalocean/packer.json
  images/capi/packer/digitalocean/ubuntu-2004.json
  images/capi/packer/hcloud/ubuntu-2004.json
  images/capi/packer/nutanix/ubuntu-2004.json
  images/capi/packer/oci/packer.json
  images/capi/packer/oci/ubuntu-2004.json
  images/capi/packer/openstack/ubuntu-2004.json
  images/capi/packer/outscale/ubuntu-2004.json
  images/capi/packer/ova/ubuntu-2004-efi.json
  images/capi/packer/ova/ubuntu-2004.json
  images/capi/packer/qemu/README.md
  images/capi/packer/qemu/qemu-ubuntu-2004-efi.json
  images/capi/packer/qemu/qemu-ubuntu-2004.json
  images/capi/packer/raw/raw-ubuntu-2004-efi.json
  images/capi/packer/raw/raw-ubuntu-2004.json
  images/capi/packer/vultr/packer.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1827 Make kubelet log redirection optional for windows
  images/capi/ansible/windows/roles/kubernetes/defaults/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/packer/config/windows/ansible-args-windows.json
  images/capi/packer/ova/packer-windows.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1841 Add wait for vSphere reachable to ci-ova.sh
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1843 fix: adding defaults and type check to some bool checks and making a few 'and' statements into lists
  images/capi/ansible/roles/node/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/debian.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/rpm_repos.yml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1845 Update nightly gcp jobs
  images/capi/packer/gce/ci/nightly/overwrite-1-30.json
  images/capi/packer/gce/ci/nightly/overwrite-1-31.json
  images/capi/packer/gce/ci/nightly/overwrite-1-32.json
  images/capi/packer/gce/ci/nightly/overwrite-1-33.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1836 Fix pypy installer on Flatcar Azure
  images/capi/ansible/roles/python/defaults/main.yml
  images/capi/ansible/roles/python/tasks/flatcar.yml
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1838 fix: builder user remenants should not be present in node images
  images/capi/packer/maas/packer.json.tmpl
  images/capi/packer/nutanix/packer.json.tmpl
  images/capi/packer/qemu/packer.json.tmpl
  images/capi/packer/raw/packer.json.tmpl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1846 Update docs for image-builder v0.1.46
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm
