Repository kubernetes-sigs/image-builder, pull requests merged in 2025-06, with the labels that each got.

#1752 Make kubelet starting as a windows service
  images/capi/ansible/windows/roles/kubernetes/defaults/main.yml
  images/capi/ansible/windows/roles/kubernetes/tasks/sc.yml
  images/capi/ansible/windows/roles/kubernetes/templates/RestartKubelet.ps1
Labels: size/M, cncf-cla: yes, approved, lgtm

#1767 capi: adjust ova script for community infrastructure and fixes
  images/capi/packer/ova/linux/rockylinux/http/9/ks.cfg.tmpl
  images/capi/packer/ova/packer-node.json
  images/capi/packer/ova/rockylinux-9.json
  images/capi/scripts/ci-ova.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1774 Remove Ubuntu 20.04 from GCP provider
  docs/book/src/capi/providers/gcp.md
  images/capi/Makefile
  images/capi/packer/gce/ubuntu-2004.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1778 Increas task_timeout for large ISOs or slow Proxmox Servers
  images/capi/packer/proxmox/packer.json.tmpl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1779 build 1.33.2/1.32.6/1.31.10/1.30.14 k8s images for capg
  images/capi/packer/gce/ci/nightly/overwrite-1-30.json
  images/capi/packer/gce/ci/nightly/overwrite-1-31.json
  images/capi/packer/gce/ci/nightly/overwrite-1-32.json
  images/capi/packer/gce/ci/nightly/overwrite-1-33.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1786 MAAS: Update ubuntu 24.04 iso version
  images/capi/packer/maas/maas-ubuntu-2404-efi.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1787 Remove Photon-3 OS as end of life March 2024
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/packer/ova/photon-3.json
Labels: size/M, cncf-cla: yes, approved, lgtm

#1789 Remove Photon3 references from goss
  images/capi/ansible/roles/node/defaults/main.yml
  images/capi/packer/goss/goss-vars.yaml
Labels: size/S, cncf-cla: yes, approved, lgtm

#1783 Remove Centos-7 due to end of life June 2024
  docs/book/src/capi/providers/aws.md
  docs/book/src/capi/providers/digitalocean.md
  docs/book/src/capi/providers/hcloud.md
  docs/book/src/capi/providers/vsphere.md
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/ami/centos-7.json
  images/capi/packer/azure/centos-7-gen2.json
  images/capi/packer/azure/centos-7.json
  images/capi/packer/azure/scripts/init-sig.sh
  images/capi/packer/digitalocean/centos-7.json
  images/capi/packer/hcloud/centos-7.json
  images/capi/packer/ova/centos-7.json
  images/capi/packer/qemu/qemu-centos-7.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1788 Remove Ubuntu 23.04 as end of life Jan 2024
  images/capi/Makefile
  images/capi/packer/qemu/qemu-ubuntu-2304.json
Labels: size/S, cncf-cla: yes, approved, lgtm

#1790 Remove Mariner-2 as end-of-life
  images/capi/Makefile
  images/capi/azure_targets.sh
  images/capi/packer/azure/mariner-2-gen2.json
  images/capi/packer/azure/mariner-2.json
  images/capi/packer/azure/scripts/init-sig.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1784 MAAS: Support both UEFI and BIOS boot modes in setup-bootloader
  images/capi/ansible/roles/providers/files/maas/curtin/curtin-hooks
  images/capi/ansible/roles/providers/files/maas/curtin/setup-bootloader
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm
