Repository kubernetes-sigs/image-builder, pull requests merged in 2025-07, with the labels that each got.

#1781 Update the OVA test script to dynamically detect targets to test
  images/capi/scripts/ci-ova.sh
Labels: size/S, cncf-cla: yes, approved, lgtm

#1800 Force setting windows_admin_password for OVA and Nutanix
  images/capi/Makefile
  images/capi/hack/windows-unattend.py
  images/capi/packer/nutanix/packer-windows.json
  images/capi/packer/nutanix/windows/windows-2022/autounattend.xml
  images/capi/packer/ova/packer-windows.json
  images/capi/packer/ova/windows/windows-2019-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2019/autounattend.xml
  images/capi/packer/ova/windows/windows-2022-efi/autounattend.xml
  images/capi/packer/ova/windows/windows-2022/autounattend.xml
Labels: size/M, committee/security-response, cncf-cla: yes, approved, lgtm

#1803 Update docs for v0.1.45 release
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm

#1798 Work around 2022 4B image
  images/capi/ansible/windows/roles/kubernetes/templates/RestartKubelet.ps1
  images/capi/ansible/windows/roles/systemprep/tasks/main.yml
Labels: size/S, tide/merge-method-squash, cncf-cla: yes, approved, lgtm

#1806 Fix gvisor installation and add goss test
  images/capi/ansible/roles/containerd/tasks/main.yml
  images/capi/packer/ami/packer.json
  images/capi/packer/azure/packer.json
  images/capi/packer/config/ansible-args.json
  images/capi/packer/gce/packer.json
  images/capi/packer/goss/goss-command.yaml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/hcloud/packer.json
  images/capi/packer/huaweicloud/packer.json
  images/capi/packer/nutanix/packer.json.tmpl
  images/capi/packer/oci/packer.json
  images/capi/packer/openstack/packer.json
  images/capi/packer/outscale/packer.json
  images/capi/packer/ova/packer-node.json
  images/capi/packer/raw/packer.json.tmpl
  images/capi/packer/scaleway/packer.json
Labels: ok-to-test, size/M, cncf-cla: yes, approved, lgtm

#1807 Add AndiDog as a reviewer for image-builder
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1809 Add note to README regarding access restrictions on the office hours doc
  README.md
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1802 Updated Azure CI tests to automatically detect targets
  images/capi/azure_targets.sh
  images/capi/scripts/ci-azure-e2e.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1812 Exclude grub packages from apt-mark hold
  images/capi/ansible/roles/sysprep/tasks/debian.yml
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1801 Enable RockyLinux-8 on OVA tests
  images/capi/packer/ova/rockylinux-8.json
  images/capi/scripts/ci-ova.sh
Labels: size/S, tide/merge-method-squash, cncf-cla: yes, approved, lgtm

#1814 feat(outscale): add OS ubuntu-24.04
  README.md
  docs/book/src/capi/providers/3dsoutscale.md
  images/capi/Makefile
  images/capi/packer/outscale/ubuntu-2404.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1820 Update security contacts to current maintainers
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1819 Add more debug file for windows node
  images/capi/ansible/windows/roles/debug/defaults/main.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm
