Repository kubernetes-sigs/image-builder, pull requests merged in 2025-02, with the labels that each got.

#1673 Support customize Windows admin password when building OVA
  images/capi/hack/windows-ova-unattend.py
  images/capi/packer/ova/packer-windows.json
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1684 Set proxmox oem-id for flatcar
  docs/book/src/capi/providers/proxmox.md
  images/capi/packer/proxmox/README.md
  images/capi/packer/proxmox/flatcar.json
  images/capi/packer/proxmox/packer.json.tmpl
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1686 fix: Error building Rocky Linux 9 Image (QEMU)
  images/capi/packer/qemu/linux/rockylinux/http/9/ks.cfg.tmpl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1687 feat(outscale): parametrize image owner and use timestamp as suffix
  images/capi/packer/outscale/packer.json
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1691 Fix proxmox quotes
  images/capi/packer/proxmox/packer.json.tmpl
Labels: ok-to-test, cncf-cla: yes, size/XS, approved, lgtm

#1665 Proxmox add config variables
  docs/book/src/capi/providers/proxmox.md
  images/capi/packer/proxmox/packer.json.tmpl
Labels: size/S, ok-to-test, cncf-cla: yes, approved, lgtm

#1680 Update goss
  docs/book/src/capi/goss/goss.md
  images/capi/packer/config.pkr.hcl
  images/capi/packer/config/goss-args.json
  images/capi/packer/gce/packer.json
  images/capi/packer/goss/goss-files.yaml
  images/capi/packer/goss/goss-package.yaml
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/nutanix/packer-windows.json
  images/capi/packer/ova/packer-windows.json
  images/capi/scripts/ci-disable-goss-inspect.json
  images/capi/scripts/ci-goss-populate.sh
Labels: size/M, cncf-cla: yes, approved, lgtm

#1692 Support for Huaweicloud
  docs/book/src/capi/capi.md
  docs/book/src/capi/providers/huaweicloud.md
  images/capi/Makefile
  images/capi/ansible/roles/providers/tasks/huaweicloud.yml
  images/capi/ansible/roles/providers/tasks/main.yml
  images/capi/ansible/roles/sysprep/tasks/main.yml
  images/capi/packer/config/ansible-args.json
  images/capi/packer/config/common.json
  images/capi/packer/goss/goss-vars.yaml
  images/capi/packer/huaweicloud/config.pkr.hcl
  images/capi/packer/huaweicloud/packer.json
  images/capi/packer/huaweicloud/ubuntu-2204.json
Labels: size/L, cncf-cla: yes, approved, lgtm

#1693 Update docs for image-builder v0.1.41
  RELEASE.md
  docs/book/src/capi/container-image.md
  docs/book/src/capi/releasing.md
Labels: size/S, cncf-cla: yes, approved, lgtm
